In [2]:
import pandas as pd

# 0227 실험 결과

## gemma-3-12b-it

In [13]:
answered_file_path = "/workspace/data/train_sample_processed/gemma-3-12b-it/answered_image_ambiguous_sentence_wsd_set_promp2.csv"

answered_df = pd.read_csv(answered_file_path)

In [14]:
accuracy = (answered_df["gold_sense"] == answered_df["predicted_answer"]).sum() / len(answered_df)
print(accuracy)

0.9215686274509803

In [15]:
answered_file_path = "/workspace/data/train_sample_processed/gemma-3-12b-it/answered_ambiguous_sentence_wsd_set_promp2.csv"

answered_df = pd.read_csv(answered_file_path)

In [16]:
accuracy = (answered_df["gold_sense"] == answered_df["predicted_answer"]).sum() / len(answered_df)
print(accuracy)

0.5882352941176471

In [19]:
answered_file_path = "/workspace/data/train_sample_processed/gemma-3-12b-it/answered_ambiguous_sentence_wsd_set_broad_caption.csv"

answered_df = pd.read_csv(answered_file_path)

In [20]:
accuracy = (answered_df["gold_sense"] == answered_df["predicted_answer"]).sum() / len(answered_df)
print(accuracy)

0.9019607843137255

In [21]:
answered_file_path = "/workspace/data/train_sample_processed/gemma-3-12b-it/answered_ambiguous_sentence_wsd_set_specific_caption.csv"

answered_df = pd.read_csv(answered_file_path)

In [22]:
accuracy = (answered_df["gold_sense"] == answered_df["predicted_answer"]).sum() / len(answered_df)
print(accuracy)

0.8627450980392157

## gemma-3-27b-it

In [7]:
answered_file_path = "/workspace/data/train_sample_processed/gemma-3-27b-it/answered_ambiguous_sentence_wsd_set.csv"

answered_df = pd.read_csv(answered_file_path)

In [8]:
accuracy = (answered_df["gold_sense"] == answered_df["predicted_answer"]).sum() / len(answered_df)
print(accuracy)

0.5686274509803921

In [9]:
answered_file_path = "/workspace/data/train_sample_processed/gemma-3-27b-it/answered_image_ambiguous_sentence_wsd_set.csv"

answered_df = pd.read_csv(answered_file_path)

In [10]:
accuracy = (answered_df["gold_sense"] == answered_df["predicted_answer"]).sum() / len(answered_df)
print(accuracy)

0.7647058823529411

결론적으로 이미지를 context로 주었을 때 정확도가 꽤 높아졌다.

어쨌든 이미지를 context로 주었을 때 성능이 향상되는 효과를 보았으니 다음에는 이미지를 caption으로 주었을 때 성능이 어찌되는지 검증해봅시다.

* case 1: caption을 무작정 생성해서 주었을 때
* case 2: wsd를 수행해야 할 문장과 주목할 단어를 주고 caption을 생성하도록 하였을 때

그 다음에는 gemma3가 아닌 다른 모델로도 실험해보기

# 0403 실험 결과

* 각 샘플에 가장 적합한 품사를 찾는 task
* 동시에 해당 샘플이 의미가 있는지 찾는 task를 수행

## gemma3-4b

In [15]:
pos_gemma3_4b = pd.read_csv("/workspace/data/dataset_construction_train/test_set_pos_inference_results_gemma3-4b.csv")

pos_gemma3_4b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,prompt,label,answer
0,461,buzzer,"{""noun_senses"": [""a push button at an outer do...",image.4566.jpg,2,The buzzer sounded just as the game ended.,\nWord: buzzer\nNoun Senses:\n1) a push button...,noun,"Okay, let's analyze the image and the word ""bu..."
1,1314,race,"{""verb_senses"": [""move fast"", ""compete in a ra...",image.8102.jpg,2,They decided to race through the park before t...,\nWord: race\nNoun Senses:\n1) the sport of en...,verb,"Okay, let's analyze the word ""race"" in the con..."
2,142,ambush,"{""verb_senses"": [""wait in hiding to attack"", ""...",image.2146.jpg,1,The specialized team was prepared to ambush th...,\nWord: ambush\nNoun Senses:\n1) the act of co...,verb,"Okay, let's analyze the image and the word ""am..."
3,2443,yarn,"{""noun_senses"": [""the act of giving an account...",image.770.jpg,2,She spent the whole afternoon spinning a long ...,\nWord: yarn\nNoun Senses:\n1) the act of givi...,noun,"Okay, let's analyze the image and the word ""ya..."
4,1999,browse,"{""verb_senses"": [""shop around; not necessarily...",image.4118.jpg,1,The visitors spent the entire afternoon at the...,\nWord: browse\nNoun Senses:\n1) vegetation (s...,verb,"Okay, let's analyze the word ""browse"" in the c..."
...,...,...,...,...,...,...,...,...,...
95,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",\nWord: breakdown\nNoun Senses:\n1) the act of...,noun,"Okay, let's analyze the word ""breakdown"" in th..."
96,993,mead,"{""noun_senses"": [""United States anthropologist...",image.4290.jpg,-1,NaN,\nWord: mead\nNoun Senses:\n1) United States a...,invalid,"Okay, let's analyze the image and the provided..."
97,2041,listing,"{""noun_senses"": [""a database containing an ord...",image.4916.jpg,2,The listing of the donor names required a grea...,\nWord: listing\nNoun Senses:\n1) a database c...,noun,"Okay, let's analyze the image and the word ""li..."
98,1724,prostration,"{""noun_senses"": [""an abrupt failure of functio...",image.4045.jpg,3,The diplomat entered the chamber and met the E...,\nWord: prostration\nNoun Senses:\n1) an abrup...,noun,"Okay, let's analyze the word ""prostration"" in ..."
99,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,\nWord: lithography\nNoun Senses:\n1) a method...,invalid,"Okay, let's analyze the word ""lithography"" in ..."

In [16]:
# 자연어 속에 묻혀있는 정답 찾기
processed_answers = list()
for index, row in pos_gemma3_4b.iterrows():
    answer = row["answer"]
    
    if "Answer:" in answer:
        processed_answer = answer.split("Answer:")[-1].strip()
    else:
        processed_answer = "incomplete"
    processed_answers.append(processed_answer)

pos_gemma3_4b["predicted_answer"] = processed_answers

In [17]:
(pos_gemma3_4b["predicted_answer"] == pos_gemma3_4b["label"]).sum() / len(pos_gemma3_4b)

np.float64(0.74)

In [18]:
pos_gemma3_4b.loc[pos_gemma3_4b["predicted_answer"] != pos_gemma3_4b["label"], ["label", "predicted_answer"]]

      label predicted_answer
1      verb             noun
7      noun             verb
8   invalid             noun
12     noun             verb
14     verb             noun
21  invalid             noun
25  invalid             noun
27     noun             verb
29  invalid             noun
31  invalid             verb
40     noun       incomplete
43     noun             verb
49     verb             noun
51  invalid             verb
56  invalid             noun
57  invalid             noun
62  invalid             verb
73  invalid             noun
81     noun             verb
85  invalid             noun
86  invalid             noun
92     noun             verb
93  invalid             noun
96  invalid             noun
97     noun             verb
99  invalid             noun

In [20]:
wrong_df = pos_gemma3_4b.loc[pos_gemma3_4b["predicted_answer"] != pos_gemma3_4b["label"]]
wrong_df.to_csv("/workspace/data/dataset_construction_train/inference/test_set_pos_inference_results_gemma3-4b_wrong_predictions.csv", index=False)

## gemma3-4b-tuned

In [11]:
pos_gemma3_4b = pd.read_csv("/workspace/data/dataset_construction_train/test_set_pos_inference_results_gemma3-4b-tuned.csv")

pos_gemma3_4b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,prompt,label,answer
0,461,buzzer,"{""noun_senses"": [""a push button at an outer do...",image.4566.jpg,2,The buzzer sounded just as the game ended.,\nWord: buzzer\nNoun Senses:\n1) a push button...,noun,Answer: noun
1,1314,race,"{""verb_senses"": [""move fast"", ""compete in a ra...",image.8102.jpg,2,They decided to race through the park before t...,\nWord: race\nNoun Senses:\n1) the sport of en...,verb,Answer: invalid
2,142,ambush,"{""verb_senses"": [""wait in hiding to attack"", ""...",image.2146.jpg,1,The specialized team was prepared to ambush th...,\nWord: ambush\nNoun Senses:\n1) the act of co...,verb,Answer: invalid
3,2443,yarn,"{""noun_senses"": [""the act of giving an account...",image.770.jpg,2,She spent the whole afternoon spinning a long ...,\nWord: yarn\nNoun Senses:\n1) the act of givi...,noun,Answer: noun
4,1999,browse,"{""verb_senses"": [""shop around; not necessarily...",image.4118.jpg,1,The visitors spent the entire afternoon at the...,\nWord: browse\nNoun Senses:\n1) vegetation (s...,verb,Answer: verb
...,...,...,...,...,...,...,...,...,...
95,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",\nWord: breakdown\nNoun Senses:\n1) the act of...,noun,Answer: noun
96,993,mead,"{""noun_senses"": [""United States anthropologist...",image.4290.jpg,-1,NaN,\nWord: mead\nNoun Senses:\n1) United States a...,invalid,Answer: noun
97,2041,listing,"{""noun_senses"": [""a database containing an ord...",image.4916.jpg,2,The listing of the donor names required a grea...,\nWord: listing\nNoun Senses:\n1) a database c...,noun,Answer: invalid
98,1724,prostration,"{""noun_senses"": [""an abrupt failure of functio...",image.4045.jpg,3,The diplomat entered the chamber and met the E...,\nWord: prostration\nNoun Senses:\n1) an abrup...,noun,Answer: noun
99,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,\nWord: lithography\nNoun Senses:\n1) a method...,invalid,Answer: invalid

In [12]:
# 자연어 속에 묻혀있는 정답 찾기
processed_answers = list()
for index, row in pos_gemma3_4b.iterrows():
    answer = row["answer"]
    
    if "Answer:" in answer:
        processed_answer = answer.split("Answer:")[-1].strip()
    else:
        processed_answer = "incomplete"
    processed_answers.append(processed_answer)

pos_gemma3_4b["predicted_answer"] = processed_answers

In [13]:
(pos_gemma3_4b["predicted_answer"] == pos_gemma3_4b["label"]).sum() / len(pos_gemma3_4b)

np.float64(0.61)

## gemma3-12b

In [2]:
pos_gemma3_12b = pd.read_csv("/workspace/data/dataset_construction_train/test_set_pos_inference_results_gemma3-12b.csv")

pos_gemma3_12b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,prompt,label,answer
0,461,buzzer,"{""noun_senses"": [""a push button at an outer do...",image.4566.jpg,2,The buzzer sounded just as the game ended.,\nWord: buzzer\nNoun Senses:\n1) a push button...,noun,The image shows two small devices with wires a...
1,1314,race,"{""verb_senses"": [""move fast"", ""compete in a ra...",image.8102.jpg,2,They decided to race through the park before t...,\nWord: race\nNoun Senses:\n1) the sport of en...,verb,Let's analyze the image and the provided word ...
2,142,ambush,"{""verb_senses"": [""wait in hiding to attack"", ""...",image.2146.jpg,1,The specialized team was prepared to ambush th...,\nWord: ambush\nNoun Senses:\n1) the act of co...,verb,"Let's analyze the image and the word ""ambush"" ..."
3,2443,yarn,"{""noun_senses"": [""the act of giving an account...",image.770.jpg,2,She spent the whole afternoon spinning a long ...,\nWord: yarn\nNoun Senses:\n1) the act of givi...,noun,The image shows balls of yarn in different col...
4,1999,browse,"{""verb_senses"": [""shop around; not necessarily...",image.4118.jpg,1,The visitors spent the entire afternoon at the...,\nWord: browse\nNoun Senses:\n1) vegetation (s...,verb,Let's analyze the image and the provided word ...
...,...,...,...,...,...,...,...,...,...
95,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",\nWord: breakdown\nNoun Senses:\n1) the act of...,noun,"Let's analyze the image and the word ""breakdow..."
96,993,mead,"{""noun_senses"": [""United States anthropologist...",image.4290.jpg,-1,NaN,\nWord: mead\nNoun Senses:\n1) United States a...,invalid,The image shows a bottle and a glass of a gold...
97,2041,listing,"{""noun_senses"": [""a database containing an ord...",image.4916.jpg,2,The listing of the donor names required a grea...,\nWord: listing\nNoun Senses:\n1) a database c...,noun,The image shows a snippet of BASIC code. The c...
98,1724,prostration,"{""noun_senses"": [""an abrupt failure of functio...",image.4045.jpg,3,The diplomat entered the chamber and met the E...,\nWord: prostration\nNoun Senses:\n1) an abrup...,noun,"Let's analyze the image and the word ""prostrat..."
99,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,\nWord: lithography\nNoun Senses:\n1) a method...,invalid,The image shows a vintage map of Odessa. The m...

In [3]:
# 자연어 속에 묻혀있는 정답 찾기
processed_answers = list()
for index, row in pos_gemma3_12b.iterrows():
    answer = row["answer"]
    
    if "Answer:" in answer:
        processed_answer = answer.split("Answer:")[-1].strip()
    else:
        processed_answer = "invalid"
    processed_answers.append(processed_answer)

pos_gemma3_12b["predicted_answer"] = processed_answers

In [4]:
(pos_gemma3_12b["predicted_answer"] == pos_gemma3_12b["label"]).sum() / len(pos_gemma3_12b)

np.float64(0.73)

In [5]:
pos_gemma3_12b.loc[pos_gemma3_12b["predicted_answer"] != pos_gemma3_12b["label"], ["label", "predicted_answer"]]

      label predicted_answer
8   invalid             noun
14     verb             noun
18     noun          invalid
21  invalid             noun
23     noun          invalid
25  invalid             noun
29  invalid             noun
31  invalid             noun
32     noun          invalid
34     noun          invalid
43     noun             verb
47     noun          invalid
50     noun             verb
51  invalid             noun
56  invalid             noun
57  invalid             noun
62  invalid             noun
73  invalid             noun
76     noun          invalid
81     noun             verb
85  invalid             verb
86  invalid             noun
90     noun          invalid
92     noun             verb
96  invalid             noun
98     noun          invalid
99  invalid             noun

In [10]:
inspect_index = 14
print(pos_gemma3_12b.loc[inspect_index]["word"])
print(pos_gemma3_12b.loc[inspect_index]["senses"])
print(pos_gemma3_12b.loc[inspect_index]["answer"])

desolate
{"verb_senses": ["leave someone who needs or counts on you; leave in the lurch", "reduce in population", "cause extensive destruction or ruin utterly"], "gold_pos": "verb", "noun_senses": []}
Let's analyze the image and the provided word senses to determine the most appropriate part of speech.

The image depicts a raging forest fire, with flames engulfing trees and creating a scene of destruction.

1. **'In practice, which part of speech does the image refer to?'** The image primarily represents a state of being – a place that has been utterly ruined and destroyed. This aligns more closely with the noun sense of "desolate," meaning a deserted or bleak place. The image doesn't show an action being performed *on* something, but rather the *result* of an action (the fire).

2. **'In which POS can this word be used in a way that makes it more ambiguous within a sentence?'** Let's consider the ambiguity of each part of speech:
    *   **Noun:** "The desolate landscape was a testament to the fire's power." - This is a clear and direct connection to the image.
    *   **Verb:** "The fire desolated the forest." - While grammatically correct, it's less evocative and less directly related to the image's overall feeling of emptiness and ruin. The verb sense implies an action *causing* desolation, whereas the image *shows* the desolation.

Considering both aspects, the image strongly suggests the noun sense of "desolate" (a deserted or bleak place). The noun form allows for a more nuanced and ambiguous description of the scene, as it focuses on the state of the environment rather than the action that caused it. The verb sense, while possible, is less directly representative of the image's core meaning.

Answer: noun

## gemma3-27b

In [3]:
pos_gemma3_27b = pd.read_csv("/workspace/data/dataset_construction_train/test_set_pos_inference_results_gemma3-27b.csv")

pos_gemma3_27b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,prompt,label,answer
0,461,buzzer,"{""noun_senses"": [""a push button at an outer do...",image.4566.jpg,2,The buzzer sounded just as the game ended.,\nWord: buzzer\nNoun Senses:\n1) a push button...,noun,The image shows what appears to be a small spe...
1,1314,race,"{""verb_senses"": [""move fast"", ""compete in a ra...",image.8102.jpg,2,They decided to race through the park before t...,\nWord: race\nNoun Senses:\n1) the sport of en...,verb,The image shows cyclists competing on a track....
2,142,ambush,"{""verb_senses"": [""wait in hiding to attack"", ""...",image.2146.jpg,1,The specialized team was prepared to ambush th...,\nWord: ambush\nNoun Senses:\n1) the act of co...,verb,The image depicts a group of armed men in a fi...
3,2443,yarn,"{""noun_senses"": [""the act of giving an account...",image.770.jpg,2,She spent the whole afternoon spinning a long ...,\nWord: yarn\nNoun Senses:\n1) the act of givi...,noun,"The image shows balls of yarn, which are twist..."
4,1999,browse,"{""verb_senses"": [""shop around; not necessarily...",image.4118.jpg,1,The visitors spent the entire afternoon at the...,\nWord: browse\nNoun Senses:\n1) vegetation (s...,verb,Let's analyze the image and the given senses o...
...,...,...,...,...,...,...,...,...,...
95,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",\nWord: breakdown\nNoun Senses:\n1) the act of...,noun,Let's analyze the image and the given senses o...
96,993,mead,"{""noun_senses"": [""United States anthropologist...",image.4290.jpg,-1,NaN,\nWord: mead\nNoun Senses:\n1) United States a...,invalid,The image shows a bottle and a glass of a yell...
97,2041,listing,"{""noun_senses"": [""a database containing an ord...",image.4916.jpg,2,The listing of the donor names required a grea...,\nWord: listing\nNoun Senses:\n1) a database c...,noun,"The image shows a computer program listing, sp..."
98,1724,prostration,"{""noun_senses"": [""an abrupt failure of functio...",image.4045.jpg,3,The diplomat entered the chamber and met the E...,\nWord: prostration\nNoun Senses:\n1) an abrup...,noun,Let's analyze the image and the provided sense...
99,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,\nWord: lithography\nNoun Senses:\n1) a method...,invalid,"The image shows a map titled ""Планъ города Оде..."

In [4]:
# 자연어 속에 묻혀있는 정답 찾기
processed_answers = list()
for index, row in pos_gemma3_27b.iterrows():
    answer = row["answer"]
    
    if "Answer:" in answer:
        processed_answer = answer.split("Answer:")[-1].strip()
    else:
        processed_answer = "incomplete"
    processed_answers.append(processed_answer)

pos_gemma3_27b["predicted_answer"] = processed_answers

In [5]:
(pos_gemma3_27b["predicted_answer"] == pos_gemma3_27b["label"]).sum() / len(pos_gemma3_27b)

np.float64(0.54)

In [6]:
pos_gemma3_27b.loc[pos_gemma3_27b["predicted_answer"] != pos_gemma3_27b["label"], ["word_index","label", "predicted_answer"]]

    word_index    label predicted_answer
0          461     noun          invalid
1         1314     verb             noun
6          254     noun          invalid
9         2512     noun          invalid
11         388     noun          invalid
12        2665     noun          invalid
13         344     noun          invalid
17        1054     noun          invalid
19        2198     noun             verb
20         221     noun          invalid
26         901     noun          invalid
27         275     noun             verb
30        1370     noun          invalid
31         456  invalid             noun
32        1429     noun          invalid
33        1803     noun          invalid
34         321     noun          invalid
37        1996     noun          invalid
42        2358     noun          invalid
48         850     noun          invalid
49        1723     verb             noun
50         418     noun          invalid
51         623  invalid             noun
53        1252     noun          invalid
58        2508     noun          invalid
59        1753     noun          invalid
60          50     noun          invalid
62        1401  invalid             verb
63        2617     noun          invalid
64         724     noun          invalid
69        2544     noun          invalid
70        1658     noun          invalid
71        2543     noun          invalid
72        1976     noun          invalid
75        1163     noun          invalid
76         764     noun          invalid
77        2381     noun          invalid
81        2379     noun          invalid
85        2494  invalid             verb
88        2374     noun          invalid
90         587     noun          invalid
92        1277     noun          invalid
93        1488  invalid             noun
94         306     noun          invalid
96         993  invalid             noun
99        2741  invalid             noun

# 0410 실험 결과

valid invalid 기준을 명확하게 한 후 이 기준을 4개로 나누어 각각에 대해 example을 주고 분류하도록 하였다.

In [2]:
import pandas as pd

def calculate_accuracy(df):
    processed_answers = list()
    for index, row in df.iterrows():
        answer = row["answer"]
        
        if "Answer:" in answer:
            processed_answer = answer.split("Answer:")[-1].strip()
        else:
            processed_answer = "incomplete"
        processed_answers.append(processed_answer)

    df["predicted_answer"] = processed_answers

    accuracy = (df["predicted_answer"] == df["label"]).sum() / len(df)
    return accuracy

## 기준 1: 이미지가 여러 개의 sense를 가리킬 수 있음

### gemma3-27b 프롬프트 v1

프롬프트 구조:

```
Word: {word}
---
Noun Senses:
{noun_sense_list}
---
Verb Senses:
{verb_sense_list}
---
Distinguish whether the given word is valid for visual word sense disambiguation. 
Decide based on the following criteria:
* If the given image for the word can not exclusively refer to one of the senses of the word, it is invalid for visual word sense disambiguation.

Here are some examples of valid and invalid words for visual word sense disambiguation:
{example1}
---
{example2}
---
{example3}
---
{example4}

Think step by step and provide a detailed explanation for your answer. Then, give the final answer in the format of 'Answer: Valid' or 'Answer: Invalid'.
```

In [3]:
valid1_27b = pd.read_csv("/workspace/data/dataset_construction_train/inference/invalid1_results_gemma3-27b-tuned.csv")

valid1_27b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,label,prompt,answer
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg,1,The moorhen blended well with the surrounding ...,Valid,\nWord: moorhen\n---\nNoun Senses:\n1) black g...,The image shows a black bird with a red beak i...
1,11,upset,"{""verb_senses"": [""disturb the balance or stabi...",image.185.jpg,6,The unexpected performance by the rookie is go...,Valid,\nWord: upset\n---\nNoun Senses:\n1) an unhapp...,"Let's analyze the image and the word ""kindness..."
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",Valid,\nWord: breakdown\n---\nNoun Senses:\n1) the a...,The image shows a street scene with cars and a...
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg,3,The craftsman relied on the beater to ensure a...,Valid,\nWord: beater\n---\nNoun Senses:\n1) a worker...,"The image shows a woman operating a loom, a de..."
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg,1,He always enjoyed sprat with a squeeze of lemon.,Valid,\nWord: sprat\n---\nNoun Senses:\n1) small fat...,"The image shows a small, silvery fish. The wor..."
...,...,...,...,...,...,...,...,...,...
709,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,Invalid,\nWord: lithography\n---\nNoun Senses:\n1) a m...,The image shows a map. A map is a visual repre...
710,2742,attic,"{""noun_senses"": [""floor consisting of open spa...",image.4755.jpg,1,He spent the entire afternoon focused on the a...,Valid,\nWord: attic\n---\nNoun Senses:\n1) floor con...,The image shows the interior of a space direct...
711,2744,fall,"{""verb_senses"": [""descend in free fall under t...",image.14268.jpg,1,The giant will fall before the day is over.,Valid,\nWord: fall\n---\nNoun Senses:\n1) the season...,"The image shows a person in mid-air, appearing..."
712,2746,overpower,"{""verb_senses"": [""overcome by superior force"",...",image.194.jpg,1,The sudden surge of the crowd began to overpow...,Valid,\nWord: overpower\n---\nNoun Senses:\n\n---\nV...,"The image shows a wrestling match, specificall..."
713,2756,shakedown,"{""noun_senses"": [""initial adjustments to impro...",image.2859.jpg,1,The director mentioned that a shakedown was ne...,Valid,\nWord: shakedown\n---\nNoun Senses:\n1) initi...,The image shows a rally car speeding through a...

In [5]:
acc = calculate_accuracy(valid1_27b)

print(acc)

0.6246498599439776

### gemma3-27b 프롬프트 v2

프롬프트 구조:

```
Distinguish whether the given word is valid for visual word sense disambiguation. 
Decide based on the following criteria:
* If the given image for the word can not exclusively refer to one of the senses of the word, it is invalid for visual word sense disambiguation.

Here are some examples of valid and invalid words for visual word sense disambiguation:
{example1}
---
{example2}
---
{example3}
---
{example4}
---

---Word for evaluation: {word}---
Image: <start_of_image><image_soft_token><end_of_image>
---
Noun Senses:
{noun_sense_list}
---
Verb Senses:
{verb_sense_list}

Think step by step and provide a detailed explanation for your answer. Then, give the final answer in the format of 'Answer: Valid' or 'Answer: Invalid'.
```

In [6]:
valid1_27b = pd.read_csv("/workspace/data/dataset_construction_train/inference/invalid1_results_gemma3-27b-tuned.csv")

valid1_27b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,label,prompt,answer
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg,1,The moorhen blended well with the surrounding ...,Valid,\nDistinguish whether the given word is valid ...,The image shows a bird that appears to be a mo...
1,11,upset,"{""verb_senses"": [""disturb the balance or stabi...",image.185.jpg,6,The unexpected performance by the rookie is go...,Valid,\nDistinguish whether the given word is valid ...,"The image depicts a scene of decapitation, spe..."
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",Valid,\nDistinguish whether the given word is valid ...,"The image shows a street scene with cars, a po..."
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg,3,The craftsman relied on the beater to ensure a...,Valid,\nDistinguish whether the given word is valid ...,The image shows a woman operating a loom. A lo...
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg,1,He always enjoyed sprat with a squeeze of lemon.,Valid,\nDistinguish whether the given word is valid ...,"The image shows a small, silvery fish. The nou..."
...,...,...,...,...,...,...,...,...,...
709,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,The image shows a map. Lithography is a printi...
710,2742,attic,"{""noun_senses"": [""floor consisting of open spa...",image.4755.jpg,1,He spent the entire afternoon focused on the a...,Valid,\nDistinguish whether the given word is valid ...,The image clearly shows the space directly bel...
711,2744,fall,"{""verb_senses"": [""descend in free fall under t...",image.14268.jpg,1,The giant will fall before the day is over.,Valid,\nDistinguish whether the given word is valid ...,"The image shows a person in mid-air, appearing..."
712,2746,overpower,"{""verb_senses"": [""overcome by superior force"",...",image.194.jpg,1,The sudden surge of the crowd began to overpow...,Valid,\nDistinguish whether the given word is valid ...,The image shows a wrestling match where one pe...
713,2756,shakedown,"{""noun_senses"": [""initial adjustments to impro...",image.2859.jpg,1,The director mentioned that a shakedown was ne...,Valid,\nDistinguish whether the given word is valid ...,"The image shows a car racing on a dirt road, k..."

In [7]:
acc = calculate_accuracy(valid1_27b)

print(acc)

0.6848739495798319

왜 틀렸는지는 알아야할 것 같다. 그래야 어느 방향으로 프롬프트를 개선할지 검토가 가능하지

In [9]:
# 틀린 샘플 찾기
valid1_27b[valid1_27b["predicted_answer"] == "incomplete"]

Empty DataFrame
Columns: [word_index, word, senses, gold_image, gold_sense, ambiguous_sentence, label, prompt, answer, predicted_answer]
Index: []

다행히 모든 샘플에 "Answer: ~" 형태로 답이 달린 모양

In [12]:
fn = valid1_27b.loc[(valid1_27b["predicted_answer"] != valid1_27b["label"]) & (valid1_27b["label"] == "Invalid")]

In [13]:
tp = valid1_27b.loc[(valid1_27b["predicted_answer"] == valid1_27b["label"]) & (valid1_27b["predicted_answer"] == "Invalid")]

In [14]:
fn.to_csv("/workspace/data/dataset_construction_train/inference/invalid1_results_gemma3-27b-tuned_fn_samples.csv", index=False)
tp.to_csv("/workspace/data/dataset_construction_train/inference/invalid1_results_gemma3-27b-tuned_tp_samples.csv", index=False)

## 기준 2: 이미지에 해당하는 sense가 있는가

### gemma3 27b zero shot

In [17]:
rule2_27b = pd.read_csv("/workspace/data/dataset_construction_train/inference/rule2_results_gemma3-27b_zero.csv")

rule2_27b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,label,prompt,answer
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg,1,The moorhen blended well with the surrounding ...,Valid,\nDistinguish whether the given word is valid ...,The image shows a dark-colored bird with a red...
1,11,upset,"{""verb_senses"": [""disturb the balance or stabi...",image.185.jpg,6,The unexpected performance by the rookie is go...,Valid,\nDistinguish whether the given word is valid ...,Let's analyze the image and the provided sense...
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",Valid,\nDistinguish whether the given word is valid ...,The image shows a traffic jam with a police of...
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg,3,The craftsman relied on the beater to ensure a...,Valid,\nDistinguish whether the given word is valid ...,The image shows a woman operating a loom. A lo...
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg,1,He always enjoyed sprat with a squeeze of lemon.,Valid,\nDistinguish whether the given word is valid ...,"The image shows a small, silvery fish. The nou..."
...,...,...,...,...,...,...,...,...,...
713,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,Valid,\nDistinguish whether the given word is valid ...,The image shows an old map of Odessa from 1819...
714,2742,attic,"{""noun_senses"": [""floor consisting of open spa...",image.4755.jpg,1,He spent the entire afternoon focused on the a...,Valid,\nDistinguish whether the given word is valid ...,The image shows a space under the roof of a bu...
715,2744,fall,"{""verb_senses"": [""descend in free fall under t...",image.14268.jpg,1,The giant will fall before the day is over.,Valid,\nDistinguish whether the given word is valid ...,"The image depicts a person in mid-air, appeari..."
716,2746,overpower,"{""verb_senses"": [""overcome by superior force"",...",image.194.jpg,1,The sudden surge of the crowd began to overpow...,Valid,\nDistinguish whether the given word is valid ...,The image depicts a wrestling match where one ...
717,2756,shakedown,"{""noun_senses"": [""initial adjustments to impro...",image.2859.jpg,1,The director mentioned that a shakedown was ne...,Valid,\nDistinguish whether the given word is valid ...,The image shows a rally car kicking up dirt an...

In [18]:
acc = calculate_accuracy(rule2_27b)

print(acc)

0.9637883008356546

In [19]:
fn = rule2_27b.loc[(rule2_27b["predicted_answer"] != rule2_27b["label"]) & (rule2_27b["label"] == "Invalid")]

fn

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,label,prompt,answer,predicted_answer
17,87,hoard,"{""noun_senses"": [""a secret store of valuables ...",image.1375.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,The image shows a collection of gold artifacts...,Valid
32,120,exhibition,"{""noun_senses"": [""the act of exhibiting"", ""a c...",image.1852.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,"The image shows a horse jumping competition, s...",Valid
290,1154,side,"{""noun_senses"": [""a place within a region iden...",image.10435.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,"The image shows a plate of food, specifically ...",Valid
536,2096,modern,"{""noun_senses"": [""a contemporary person"", ""a t...",image.13284.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,The image shows a black and white portrait of ...,Valid
588,2291,ruin,"{""noun_senses"": [""an irrecoverable state of de...",image.9354.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,Let's analyze the image and the provided sense...,Valid
700,2669,chin,"{""noun_senses"": [""the protruding part of the l...",image.9258.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,"The image shows a close-up of a dog's face, sp...",Valid

In [20]:
tp = rule2_27b.loc[(rule2_27b["predicted_answer"] == rule2_27b["label"]) & (rule2_27b["predicted_answer"] == "Invalid")]

tp

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,label,prompt,answer,predicted_answer
124,470,utility,"{""noun_senses"": [""a company that performs a pu...",image.3313.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,"The image depicts a mosaic scene, likely relig...",Invalid
269,1062,snorkel,"{""noun_senses"": [""breathing device consisting ...",image.10000.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,"The image shows a fire truck. The word ""snorke...",Invalid
346,1359,thompson,"{""noun_senses"": [""United States classical arch...",image.8801.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,"The image shows a Thompson submachine gun, a f...",Invalid
471,1813,arrival,"{""noun_senses"": [""accomplishment of an objecti...",image.574.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,The image shows a man playing a guitar on stag...,Invalid
505,1975,burmese,"{""noun_senses"": [""a native or inhabitant of My...",image.5917.jpg,-1,NaN,Invalid,\nDistinguish whether the given word is valid ...,The image shows a cat with a specific breed ch...,Invalid

In [21]:
fp = rule2_27b.loc[(rule2_27b["predicted_answer"] != rule2_27b["label"]) & (rule2_27b["label"] == "Valid")]

tn = rule2_27b.loc[(rule2_27b["predicted_answer"] == rule2_27b["label"]) & (rule2_27b["predicted_answer"] == "Valid")]

In [22]:
precision = len(tp) / (len(tp) + len(fp))

print(precision)

0.2

In [23]:
recall = len(tp) / (len(tp) + len(fn))

print(recall)

0.45454545454545453

In [24]:
f1_score = 2 * (precision * recall) / (precision + recall)
print(f1_score)

0.2777777777777778

### gemma3 27b few shot

In [25]:
rule2_27b = pd.read_csv("/workspace/data/dataset_construction_train/inference/rule2_results_gemma3-27b_few_shot.csv")

rule2_27b

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence,label,prompt,answer
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg,1,The moorhen blended well with the surrounding ...,Valid,\nDistinguish whether the given word is valid ...,The image shows a black bird with a red beak i...
1,11,upset,"{""verb_senses"": [""disturb the balance or stabi...",image.185.jpg,6,The unexpected performance by the rookie is go...,Valid,\nDistinguish whether the given word is valid ...,The image depicts a scene of a man holding the...
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong...",Valid,\nDistinguish whether the given word is valid ...,"The image shows a street scene with cars, a po..."
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg,3,The craftsman relied on the beater to ensure a...,Valid,\nDistinguish whether the given word is valid ...,The image shows a woman operating a loom. A lo...
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg,1,He always enjoyed sprat with a squeeze of lemon.,Valid,\nDistinguish whether the given word is valid ...,"The image shows a small, silvery fish. The nou..."
...,...,...,...,...,...,...,...,...,...
711,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN,Valid,\nDistinguish whether the given word is valid ...,The image shows a map. Lithography is a printi...
712,2742,attic,"{""noun_senses"": [""floor consisting of open spa...",image.4755.jpg,1,He spent the entire afternoon focused on the a...,Valid,\nDistinguish whether the given word is valid ...,The image shows the interior of a space direct...
713,2744,fall,"{""verb_senses"": [""descend in free fall under t...",image.14268.jpg,1,The giant will fall before the day is over.,Valid,\nDistinguish whether the given word is valid ...,"The image shows a person in mid-air, appearing..."
714,2746,overpower,"{""verb_senses"": [""overcome by superior force"",...",image.194.jpg,1,The sudden surge of the crowd began to overpow...,Valid,\nDistinguish whether the given word is valid ...,"The image shows a wrestling match, where one p..."
715,2756,shakedown,"{""noun_senses"": [""initial adjustments to impro...",image.2859.jpg,1,The director mentioned that a shakedown was ne...,Valid,\nDistinguish whether the given word is valid ...,"The image shows a car racing on a dirt track, ..."

In [26]:
acc = calculate_accuracy(rule2_27b)

print(acc)

0.952513966480447

In [27]:
fn = rule2_27b.loc[(rule2_27b["predicted_answer"] != rule2_27b["label"]) & (rule2_27b["label"] == "Invalid")]

tp = rule2_27b.loc[(rule2_27b["predicted_answer"] == rule2_27b["label"]) & (rule2_27b["predicted_answer"] == "Invalid")]

fp = rule2_27b.loc[(rule2_27b["predicted_answer"] != rule2_27b["label"]) & (rule2_27b["label"] == "Valid")]

tn = rule2_27b.loc[(rule2_27b["predicted_answer"] == rule2_27b["label"]) & (rule2_27b["predicted_answer"] == "Valid")]

In [28]:
precision = len(tp) / (len(tp) + len(fp))
recall = len(tp) / (len(tp) + len(fn))

f1_score = 2 * (precision * recall) / (precision + recall)
print(f"Precision: {precision}, Recall: {recall}, F1 Score: {f1_score}")

Precision: 0.07142857142857142, Recall: 0.2, F1 Score: 0.10526315789473682

# 0414 실험 결과

### threshold를 조정하여 성능 높여보기

기본 threshold는 0.5.

정확도 93%

verb(1)를 noun(0)으로 판정한 사례: 6

noun(0)을 verb(1)로 판정한 사례: 1

어느 정도 trade off는 나타나겠지만, threshold를 1쪽으로 더 조정하면 정확도 향상이 있을 수 있음

In [1]:
# probabilities 가져오기
import numpy as np
probabilities = np.load("/workspace/data/dataset_construction_train/inference/pos_tagging_modernbert_large_test_results/test_probabilities.npy")

In [3]:
# label 가져오기
import pandas as pd
test_df = pd.read_csv("/workspace/data/dataset_construction_train/pos_tagging_test.csv")
labels = test_df["label"].values

In [4]:
decision_threshold = 0.45
predicted_labels = (probabilities[:, 1] > decision_threshold).astype(int)

In [5]:
accuracy = (predicted_labels == labels).sum() / len(labels)
print(f"Accuracy: {accuracy}")

Accuracy: 0.93

In [11]:
decision_threshold = 0.3
predicted_labels = (probabilities[:, 1] > decision_threshold).astype(int)
accuracy = (predicted_labels == labels).sum() / len(labels)
print(f"Accuracy: {accuracy}")

Accuracy: 0.94

In [13]:
# label 0에 대한 정확도
negative_accuracy = ((predicted_labels == 0) & (labels == 0)).sum() / (labels == 0).sum()
print(f"Negative Class Accuracy: {negative_accuracy}")
# label 1에 대한 정확도
positive_accuracy = ((predicted_labels == 1) & (labels == 1)).sum() / (labels == 1).sum()
print(f"Positive Class Accuracy: {positive_accuracy}")

Negative Class Accuracy: 0.9764705882352941
Positive Class Accuracy: 0.7333333333333333

정확도에 편향성을 확인할 수 있어. class imbalance로 인한 것으로 보이고, 이 문제를 해결하려면... upscaling해봐야 할 것 같네.

## 실험 2 - verb 샘플 증강

verb sample을 증강한 후에 한 실험

In [1]:
# probabilities 가져오기
import numpy as np
probabilities = np.load("/workspace/data/dataset_construction_train/inference/pos_tagging_modernbert_large_augmentedx2_test_results/test_probabilities.npy")

In [2]:
# label 가져오기
import pandas as pd
test_df = pd.read_csv("/workspace/data/dataset_construction_train/pos_tagging_test.csv")
labels = test_df["label"].values

현재 noun을 verb로 판정한 sample이 더 많다.

따라서 threshold를 높여 noun으로 판정하기 쉽게 만들어 성능을 측정해본다.

In [3]:
decision_threshold = 0.5
predicted_labels = (probabilities[:, 1] > decision_threshold).astype(int)
accuracy = (predicted_labels == labels).sum() / len(labels)
print(f"Accuracy: {accuracy}")

Accuracy: 0.94

결국 93~94의 범위를 벗어나지 못한다.

프롬프트를 개선하여 "verb와 noun이 모두 가능할 때 sense list를 검토하여 문장에서 더 다양하게 사용 가능한 pos로 골라라"라는 내용을 추가하자.

In [4]:
negative_accuracy = ((predicted_labels == 0) & (labels == 0)).sum() / (labels == 0).sum()
print(f"Negative Class Accuracy: {negative_accuracy}")
# label 1에 대한 정확도
positive_accuracy = ((predicted_labels == 1) & (labels == 1)).sum() / (labels == 1).sum()
print(f"Positive Class Accuracy: {positive_accuracy}")

Negative Class Accuracy: 0.9411764705882353
Positive Class Accuracy: 0.9333333333333333

In [5]:
tp = ((predicted_labels == 1) & (labels == 1)).sum()
tn = ((predicted_labels == 0) & (labels == 0)).sum()
fn = ((predicted_labels == 0) & (labels == 1)).sum()
fp = ((predicted_labels == 1) & (labels == 0)).sum()

print(f"TP: {tp}, TN: {tn}, FP: {fp}, FN: {fn}")

TP: 14, TN: 80, FP: 5, FN: 1

# 0424 실험 결과

## zero shot으로 task instruction만 주어 inference하였을 때

In [1]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_pos_gemma3-27b.csv")

In [3]:
pred_to_label = {
    "noun": "n",
    "verb": "v",
    "adjective": "a",
    "adverb": "r"
}

for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = pred_to_label.get(pred_label, "invalid")
    result_df.at[index, "predicted_label"] = mapped_label

result_df["predicted_label"]

0     n
1     a
2     n
3     v
4     n
     ..
95    n
96    n
97    n
98    n
99    n
Name: predicted_label, Length: 100, dtype: str

In [4]:
acc = (result_df["predicted_label"] == result_df["gold_pos"]).sum() / len(result_df)
print(acc)

0.88

In [5]:
result_df[result_df["predicted_label"] != result_df["gold_pos"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
1,12322,white,white race,"{""n"": [""a member of the Caucasoid race"", ""the ...",image.13045.jpg,n,1,\nAmbiguous word: white\n---\nNoun senses:\n- ...,Here's my reasoning:\n\nThe image shows Brad P...,a
12,1651,mist,mist fog,"{""n"": [""a thin fog with condensation near the ...",image.4364.jpg,v,1,\nAmbiguous word: mist\n---\nNoun senses:\n- a...,The image shows a landscape with low-lying clo...,n
16,11,upset,upset success,"{""n"": [""an unhappy and worried mental state"", ...",image.185.jpg,v,6,\nAmbiguous word: upset\n---\nNoun senses:\n- ...,"The image depicts a young man, David, holding ...",a
20,4129,level,level aim,"{""n"": [""a position on a scale of intensity or ...",image.3039.jpg,v,1,\nAmbiguous word: level\n---\nNoun senses:\n- ...,Here's my analysis:\n\nThe image shows two peo...,n
24,4706,dishonour,dishonour unrighteousness,"{""n"": [""a state of shame or disgrace"", ""lackin...",image.6641.jpg,v,1,\nAmbiguous word: dishonour\n---\nNoun senses:...,"Here's my analysis of the image and the word ""...",n
30,8433,sacrifice,sacrifice kill,"{""n"": [""the act of losing or surrendering some...",image.13568.jpg,v,4,\nAmbiguous word: sacrifice\n---\nNoun senses:...,The image depicts a ritualistic scene with ind...,n
65,824,coach,coach teach,"{""n"": [""(sports) someone in charge of training...",image.8614.jpg,v,1,\nAmbiguous word: coach\n---\nNoun senses:\n- ...,Here's my analysis:\n\nThe image shows a man i...,n
81,7748,waterproofing,waterproofing protection,"{""n"": [""the act of treating something to make ...",image.14433.jpg,n,1,\nAmbiguous word: waterproofing\n---\nNoun sen...,Here's my reasoning:\n\nThe image shows a work...,v
83,5215,raft,raft float,"{""n"": [""a flat float (usually made of logs or ...",image.8767.jpg,v,2,\nAmbiguous word: raft\n---\nNoun senses:\n- a...,The image depicts several flat structures made...,n
86,6053,hanging,hanging executions,"{""n"": [""decoration that is hung (as a tapestry...",image.5107.jpg,n,2,\nAmbiguous word: hanging\n---\nNoun senses:\n...,The image depicts people suspended by ropes fr...,v
90,1205,present,present show,"{""n"": [""the period of time that is happening n...",image.5999.jpg,v,1,\nAmbiguous word: present\n---\nNoun senses:\n...,"Here's my analysis:\n\nThe word ""present"" appe...",a
94,8275,tuning,tuning calibration,"{""n"": [""(music) calibrating something (an inst...",image.2207.jpg,n,1,\nAmbiguous word: tuning\n---\nNoun senses:\n-...,The image shows a Korg chromatic tuner CA-30. ...,v

### prompt v2

In [1]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_pos2_gemma3-27b.csv")

pred_to_label = {
    "noun": "n",
    "verb": "v",
    "adjective": "a",
    "adverb": "r"
}

for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = pred_to_label.get(pred_label, "invalid")
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_pos"]).sum() / len(result_df)
print(acc)

0.9

In [2]:
result_df[result_df["predicted_label"] != result_df["gold_pos"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
1,12322,white,white race,"{""n"": [""a member of the Caucasoid race"", ""the ...",image.13045.jpg,n,1,\nAmbiguous word: white\n---\nNoun senses:\n- ...,Here's my reasoning:\n\nThe image shows Brad P...,a
12,1651,mist,mist fog,"{""n"": [""a thin fog with condensation near the ...",image.4364.jpg,v,1,\nAmbiguous word: mist\n---\nNoun senses:\n- a...,The image depicts a landscape with a thin fog-...,n
20,4129,level,level aim,"{""n"": [""a position on a scale of intensity or ...",image.3039.jpg,v,1,\nAmbiguous word: level\n---\nNoun senses:\n- ...,Here's my analysis:\n\nThe image shows a Krav ...,n
24,4706,dishonour,dishonour unrighteousness,"{""n"": [""a state of shame or disgrace"", ""lackin...",image.6641.jpg,v,1,\nAmbiguous word: dishonour\n---\nNoun senses:...,"Here's my analysis of the image and the word ""...",n
30,8433,sacrifice,sacrifice kill,"{""n"": [""the act of losing or surrendering some...",image.13568.jpg,v,4,\nAmbiguous word: sacrifice\n---\nNoun senses:...,The image depicts a ritualistic scene with ind...,n
81,7748,waterproofing,waterproofing protection,"{""n"": [""the act of treating something to make ...",image.14433.jpg,n,1,\nAmbiguous word: waterproofing\n---\nNoun sen...,Here's my reasoning:\n\nThe image shows a work...,v
83,5215,raft,raft float,"{""n"": [""a flat float (usually made of logs or ...",image.8767.jpg,v,2,\nAmbiguous word: raft\n---\nNoun senses:\n- a...,The image clearly depicts a flat structure mad...,n
86,6053,hanging,hanging executions,"{""n"": [""decoration that is hung (as a tapestry...",image.5107.jpg,n,2,\nAmbiguous word: hanging\n---\nNoun senses:\n...,The image depicts people suspended by ropes fr...,v
90,1205,present,present show,"{""n"": [""the period of time that is happening n...",image.5999.jpg,v,1,\nAmbiguous word: present\n---\nNoun senses:\n...,"Here's my analysis:\n\nThe word ""present"" in t...",a
94,8275,tuning,tuning calibration,"{""n"": [""(music) calibrating something (an inst...",image.2207.jpg,n,1,\nAmbiguous word: tuning\n---\nNoun senses:\n-...,"The image shows a Korg chromatic tuner, a devi...",v

# 0425 실험 결과

## zero shot sense labeling

In [23]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_sense_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.9

In [24]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
16,11,upset,upset success,"{""n"": [""an unhappy and worried mental state"", ...",image.185.jpg,v,6,Text Context: upset success\nAmbiguous Word: u...,The image depicts the biblical scene of David ...,2.0
37,10017,ferret,ferret mustelid,"{""n"": [""musteline mammal of prairie regions of...",image.4047.jpg,n,1,Text Context: ferret mustelid\nAmbiguous Word:...,The image shows an animal that appears to be a...,2.0
54,2533,insubordination,insubordination resistance,"{""n"": [""defiance of authority"", ""an insubordin...",image.8274.jpg,n,2,Text Context: insubordination resistance\nAmbi...,"The image depicts the mutiny on the Bounty, wh...",1.0
67,11258,vegetable,vegetable produce,"{""n"": [""edible seeds or roots or stems or leav...",image.2114.jpg,n,1,Text Context: vegetable produce\nAmbiguous Wor...,The image shows a market stall filled with var...,2.0
74,774,coca,coca shrub,"{""n"": [""a South American shrub whose leaves ar...",image.227.jpg,n,3,Text Context: coca shrub\nAmbiguous Word: coca...,"The image shows leaves, and the text context i...",1.0
82,3763,half-moon,half-moon moon,"{""n"": [""the crescent-shaped area at the base o...",image.12470.jpg,n,1,Text Context: half-moon moon\nAmbiguous Word: ...,"The image clearly shows the moon, and specific...",2.0
87,6222,deeds,deeds activity,"{""n"": [""performance of moral or religious acts...",image.5900.jpg,n,1,Text Context: deeds activity\nAmbiguous Word: ...,The image depicts a stained glass window with ...,3.0
88,1558,gear,gear wheel,"{""n"": [""a toothed wheel that engages another t...",image.6061.jpg,n,2,Text Context: gear wheel\nAmbiguous Word: gear...,The image shows a complex arrangement of tooth...,1.0
90,1205,present,present show,"{""n"": [""the period of time that is happening n...",image.5999.jpg,v,1,Text Context: present show\nAmbiguous Word: pr...,"The context is ""present show,"" referring to a ...",5.0
97,3970,aviation,aviation travel,"{""n"": [""the aggregation of a country's militar...",image.15552.jpg,n,1,Text Context: aviation travel\nAmbiguous Word:...,The image shows a fighter jet (an F-16 Fightin...,4.0

### text context 제거

In [26]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_sense2_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.88

# 0427 실험 결과

## web search sense labeling

In [3]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_sense_search2_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.92

In [6]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
1,12322,white,white race,"{""n"": [""a member of the Caucasoid race"", ""the ...",image.13045.jpg,n,1,Text Context: white race\nAmbiguous Word: whit...,"The text context refers to ""white race"" and th...",2.0
39,655,straw,straw fiber,"{""n"": [""plant fiber used e.g. for making baske...",image.4464.jpg,n,2,Text Context: straw fiber\nAmbiguous Word: str...,The image clearly shows bales of dried plant m...,1.0
54,2533,insubordination,insubordination resistance,"{""n"": [""defiance of authority"", ""an insubordin...",image.8274.jpg,n,2,Text Context: insubordination resistance\nAmbi...,"The image depicts the mutiny on the Bounty, a ...",1.0
74,774,coca,coca shrub,"{""n"": [""a South American shrub whose leaves ar...",image.227.jpg,n,3,Text Context: coca shrub\nAmbiguous Word: coca...,"The image shows leaves, and the text context i...",1.0
82,3763,half-moon,half-moon moon,"{""n"": [""the crescent-shaped area at the base o...",image.12470.jpg,n,1,Text Context: half-moon moon\nAmbiguous Word: ...,The image clearly shows a moon that is less th...,2.0
87,6222,deeds,deeds activity,"{""n"": [""performance of moral or religious acts...",image.5900.jpg,n,1,Text Context: deeds activity\nAmbiguous Word: ...,The web search results indicate the text descr...,3.0
88,1558,gear,gear wheel,"{""n"": [""a toothed wheel that engages another t...",image.6061.jpg,n,2,Text Context: gear wheel\nAmbiguous Word: gear...,The image clearly depicts a complex mechanical...,1.0
97,3970,aviation,aviation travel,"{""n"": [""the aggregation of a country's militar...",image.15552.jpg,n,1,Text Context: aviation travel\nAmbiguous Word:...,"The image shows a fighter jet, specifically an...",2.0

# 0428 실험 결과

In [9]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_sense_search3_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.89

In [10]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
12,1651,mist,mist fog,"{""n"": [""a thin fog with condensation near the ...",image.4364.jpg,v,1,Text Context: mist fog\nAmbiguous Word: mist\n...,The image depicts a landscape with low-lying c...,2.0
25,6305,astigmatism,astigmatism ametropia,"{""n"": [""(ophthalmology) impaired eyesight resu...",image.3237.jpg,n,1,Text Context: astigmatism ametropia\nAmbiguous...,The image depicts a cross-section of the human...,2.0
39,655,straw,straw fiber,"{""n"": [""plant fiber used e.g. for making baske...",image.4464.jpg,n,2,Text Context: straw fiber\nAmbiguous Word: str...,The image shows bales of dried plant material ...,1.0
47,8181,water,water release,"{""n"": [""binary compound that occurs at room te...",image.12529.jpg,v,3,Text Context: water release\nAmbiguous Word: w...,"The image clearly shows a man crying, with a v...",4.0
74,774,coca,coca shrub,"{""n"": [""a South American shrub whose leaves ar...",image.227.jpg,n,3,Text Context: coca shrub\nAmbiguous Word: coca...,"The image shows leaves, and the text context i...",1.0
82,3763,half-moon,half-moon moon,"{""n"": [""the crescent-shaped area at the base o...",image.12470.jpg,n,1,Text Context: half-moon moon\nAmbiguous Word: ...,"The image clearly shows a crescent moon, parti...",2.0
87,6222,deeds,deeds activity,"{""n"": [""performance of moral or religious acts...",image.5900.jpg,n,1,Text Context: deeds activity\nAmbiguous Word: ...,The web search results consistently point to t...,3.0
88,1558,gear,gear wheel,"{""n"": [""a toothed wheel that engages another t...",image.6061.jpg,n,2,Text Context: gear wheel\nAmbiguous Word: gear...,The image clearly shows a complex arrangement ...,1.0
90,1205,present,present show,"{""n"": [""the period of time that is happening n...",image.5999.jpg,v,1,Text Context: present show\nAmbiguous Word: pr...,The image shows a sari-sari store in the Phili...,10.0
97,3970,aviation,aviation travel,"{""n"": [""the aggregation of a country's militar...",image.15552.jpg,n,2,Text Context: aviation travel\nAmbiguous Word:...,"The image depicts a military jet, specifically...",1.0
99,801,octopus,octopus seafood,"{""n"": [""tentacles of octopus prepared as food""...",image.8471.jpg,n,1,Text Context: octopus seafood\nAmbiguous Word:...,The image shows an octopus in a bowl of ice. T...,2.0

# 0429 실험 결과

## google 검색 zero shot v3

In [4]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_sense_search3_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.89

In [5]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
16,11,upset,upset success,"{""n"": [""an unhappy and worried mental state"", ...",image.185.jpg,v,6,Text Context: upset success\nAmbiguous Word: u...,The image depicts David holding the head of Go...,3.0
20,4129,level,level aim,"{""n"": [""a position on a scale of intensity or ...",image.3039.jpg,v,4,Text Context: level aim\nAmbiguous Word: level...,"The image shows a Krav Maga training scenario,...",1.0
25,6305,astigmatism,astigmatism ametropia,"{""n"": [""(ophthalmology) impaired eyesight resu...",image.3237.jpg,n,1,Text Context: astigmatism ametropia\nAmbiguous...,The image shows how light focuses in a normal ...,2.0
26,6959,incarnation,incarnation embodiment,"{""n"": [""a new personification of a familiar id...",image.13625.jpg,n,1,Text Context: incarnation embodiment\nAmbiguou...,"The image shows a mascot costume, specifically...",3.0
39,655,straw,straw fiber,"{""n"": [""plant fiber used e.g. for making baske...",image.4464.jpg,n,2,Text Context: straw fiber\nAmbiguous Word: str...,The image clearly depicts bales of dried plant...,1.0
47,8181,water,water release,"{""n"": [""binary compound that occurs at room te...",image.12529.jpg,v,3,Text Context: water release\nAmbiguous Word: w...,"The image shows a person crying, and the text ...",4.0
74,774,coca,coca shrub,"{""n"": [""a South American shrub whose leaves ar...",image.227.jpg,n,3,Text Context: coca shrub\nAmbiguous Word: coca...,"The image shows leaves, and the text context i...",1.0
82,3763,half-moon,half-moon moon,"{""n"": [""the crescent-shaped area at the base o...",image.12470.jpg,n,1,Text Context: half-moon moon\nAmbiguous Word: ...,The web search results provide specific inform...,2.0
87,6222,deeds,deeds activity,"{""n"": [""performance of moral or religious acts...",image.5900.jpg,n,1,Text Context: deeds activity\nAmbiguous Word: ...,The image depicts a stained glass window. The ...,3.0
88,1558,gear,gear wheel,"{""n"": [""a toothed wheel that engages another t...",image.6061.jpg,n,2,Text Context: gear wheel\nAmbiguous Word: gear...,The image clearly depicts a complex system of ...,1.0
92,6522,redpoll,redpoll finch,"{""n"": [""small siskin-like finch with a red cro...",image.10309.jpg,n,1,Text Context: redpoll finch\nAmbiguous Word: r...,The image clearly shows a bird with a red crow...,2.0

In [7]:
result_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_sense_search2_gemma3-27b.csv")

for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
1,12322,white,white race,"{""n"": [""a member of the Caucasoid race"", ""the ...",image.13045.jpg,n,1,Text Context: white race\nAmbiguous Word: whit...,"The text context refers to ""white race"" and th...",2.0
39,655,straw,straw fiber,"{""n"": [""plant fiber used e.g. for making baske...",image.4464.jpg,n,2,Text Context: straw fiber\nAmbiguous Word: str...,The image clearly shows bales of dried plant m...,1.0
54,2533,insubordination,insubordination resistance,"{""n"": [""defiance of authority"", ""an insubordin...",image.8274.jpg,n,2,Text Context: insubordination resistance\nAmbi...,"The image depicts the mutiny on the Bounty, a ...",1.0
74,774,coca,coca shrub,"{""n"": [""a South American shrub whose leaves ar...",image.227.jpg,n,3,Text Context: coca shrub\nAmbiguous Word: coca...,"The image shows leaves, and the text context i...",1.0
82,3763,half-moon,half-moon moon,"{""n"": [""the crescent-shaped area at the base o...",image.12470.jpg,n,1,Text Context: half-moon moon\nAmbiguous Word: ...,The image clearly shows a moon that is less th...,2.0
87,6222,deeds,deeds activity,"{""n"": [""performance of moral or religious acts...",image.5900.jpg,n,1,Text Context: deeds activity\nAmbiguous Word: ...,The web search results indicate the text descr...,3.0
88,1558,gear,gear wheel,"{""n"": [""a toothed wheel that engages another t...",image.6061.jpg,n,2,Text Context: gear wheel\nAmbiguous Word: gear...,The image clearly depicts a complex mechanical...,1.0
97,3970,aviation,aviation travel,"{""n"": [""the aggregation of a country's militar...",image.15552.jpg,n,1,Text Context: aviation travel\nAmbiguous Word:...,"The image shows a fighter jet, specifically an...",2.0

# 0430 실험

## test set text only zeroshot 실험

In [15]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_sense_text_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.86

In [16]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
2,342,crossroads,crossroads settlement,"{""n"": [""a community of people smaller than a v...",image.7232.jpg,n,1,Text Context: crossroads settlement\nAmbiguous...,"The context is ""crossroads settlement"". This s...",4.0
5,428,crop,cattle crop,"{""n"": [""the yield from plants in a single grow...",image.7847.jpg,v,5,Text Context: cattle crop\nAmbiguous Word: cro...,"The context is ""cattle crop"". This refers to a...",3.0
11,412,torpedo,sea torpedo,"{""n"": [""a professional killer who uses a gun"",...",image.7737.jpg,n,7,Text Context: sea torpedo\nAmbiguous Word: tor...,"The context is ""sea torpedo"". This clearly ref...",6.0
39,269,balance,measuring balance,"{""n"": [""a state of equilibrium"", ""equality bet...",image.2098.jpg,n,12,Text Context: measuring balance\nAmbiguous Wor...,"The context is ""measuring balance"". This clear...",1.0
41,136,stream,rainy stream,"{""n"": [""a natural body of running water flowin...",image.5619.jpg,v,4,Text Context: rainy stream\nAmbiguous Word: st...,"The context is ""rainy stream"". The word ""strea...",5.0
43,351,anjou,anjou bunch,"{""n"": [""a former province of western France in...",image.7289.jpg,n,1,Text Context: anjou bunch\nAmbiguous Word: anj...,"The context ""anjou bunch"" strongly suggests th...",2.0
44,19,web,natural web,"{""n"": [""an intricate network suggesting someth...",image.4592.jpg,n,2,Text Context: natural web\nAmbiguous Word: web...,"The context is ""natural web"". This suggests so...",1.0
47,346,tender,ship's tender,"{""n"": [""something that can be used as an offic...",image.6519.jpg,n,5,Text Context: ship's tender\nAmbiguous Word: t...,"The context is ""ship's tender"". This refers to...",6.0
66,369,bang,person bang,"{""n"": [""a vigorous blow"", ""a sudden very loud ...",image.7414.jpg,n,3,Text Context: person bang\nAmbiguous Word: ban...,"The context ""person bang"" is extremely minimal...",2.0
77,454,circle,circle shape,"{""n"": [""ellipse in which the two axes are of e...",image.8037.jpg,n,3,Text Context: circle shape\nAmbiguous Word: ci...,"The context is simply ""circle shape"". This str...",1.0
78,241,arbor,leafy arbor,"{""n"": [""tree (as opposed to shrub)"", ""any of v...",image.6479.jpg,n,1,Text Context: leafy arbor\nAmbiguous Word: arb...,"The context is ""leafy arbor"". An arbor is desc...",3.0
82,293,dory,dory fish,"{""n"": [""a small boat of shallow draft with cro...",image.6879.jpg,n,2,Text Context: dory fish\nAmbiguous Word: dory\...,"The context is ""dory fish"". This clearly indic...",3.0
88,123,arctic,arctic boots,"{""n"": [""the regions to the north of the Arctic...",image.5518.jpg,n,2,Text Context: arctic boots\nAmbiguous Word: ar...,"The context is ""arctic boots"". The word ""arcti...",1.0
97,452,chest,chest furniture,"{""n"": [""the part of the human torso between th...",image.8015.jpg,n,4,Text Context: chest furniture\nAmbiguous Word:...,"The context is ""chest furniture"". This clearly...",2.0

## test set image zeroshot 실험

In [13]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_sense_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.96

In [14]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
5,428,crop,cattle crop,"{""n"": [""the yield from plants in a single grow...",image.7847.jpg,v,5,Text Context: cattle crop\nAmbiguous Word: cro...,"The text context is ""cattle crop"" and the imag...",4.0
41,136,stream,rainy stream,"{""n"": [""a natural body of running water flowin...",image.5619.jpg,v,4,Text Context: rainy stream\nAmbiguous Word: st...,"The text context is ""rainy stream"", and the im...",5.0
77,454,circle,circle shape,"{""n"": [""ellipse in which the two axes are of e...",image.8037.jpg,n,3,Text Context: circle shape\nAmbiguous Word: ci...,The image shows a circular opening looking up ...,1.0
82,293,dory,dory fish,"{""n"": [""a small boat of shallow draft with cro...",image.6879.jpg,n,2,Text Context: dory fish\nAmbiguous Word: dory\...,The image shows several fish with a distinctiv...,3.0

# 0502 실험 결과

## test set에 이미지 검색 결과 추가 실험

In [1]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_sense_search_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.95

그럼 그렇지. 떨어졌구나. 그럴 줄 알았다.

In [2]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
5,428,crop,cattle crop,"{""n"": [""the yield from plants in a single grow...",image.7847.jpg,v,5,Text Context: cattle crop\nAmbiguous Word: cro...,"The text context is ""cattle crop"" and the imag...",4.0
38,2,seat,eating seat,"{""n"": [""a space reserved for sitting (as in a ...",image.4432.jpg,n,3,Text Context: eating seat\nAmbiguous Word: sea...,The web search results consistently refer to t...,4.0
41,136,stream,rainy stream,"{""n"": [""a natural body of running water flowin...",image.5619.jpg,v,4,Text Context: rainy stream\nAmbiguous Word: st...,The web search results indicate the image acco...,5.0
51,302,absinthe,fennel absinthe,"{""n"": [""aromatic herb of temperate Eurasia and...",image.1705.jpg,n,1,Text Context: fennel absinthe\nAmbiguous Word:...,The web search results indicate the plant in t...,2.0
95,6,tympanum,ear tympanum,"{""n"": [""the main cavity of the ear; between th...",image.4472.jpg,n,2,Text Context: ear tympanum\nAmbiguous Word: ty...,The web search results indicate that the conte...,1.0

# 0503 실험

## sense labeling image context v2

In [3]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_sense_search2_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.98

In [4]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
20,404,sponge,living sponge,"{""n"": [""a porous mass of interlacing fibers th...",image.3157.jpg,n,4,Text Context: living sponge\nAmbiguous Word: s...,The web search results strongly indicate that ...,1.0
38,2,seat,eating seat,"{""n"": [""a space reserved for sitting (as in a ...",image.4432.jpg,n,3,Text Context: eating seat\nAmbiguous Word: sea...,"The web search results consistently point to ""...",4.0

Irelevant 판단을 먼저하고 그 후에 요약을 시키는 전법이 유효했다.

## pos 판별 실험

In [5]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_pos_gemma3-27b.csv")

pos_mapping = {
    "noun": "n",
    "verb": "v",
    "adjective": "a",
    "adverb": "r"
}
for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = pos_mapping.get(pred_label, "invalid")
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_pos"]).sum() / len(result_df)
print(acc)

0.95

In [7]:
result_df[result_df["predicted_label"] != result_df["gold_pos"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
5,428,crop,cattle crop,"{""n"": [""the yield from plants in a single grow...",image.7847.jpg,v,5,\nAmbiguous word: crop\n---\nNoun Senses:\n1) ...,The image shows a field with sheep grazing. Th...,n
7,388,flight,birds flight,"{""n"": [""a formation of aircraft in flight"", ""a...",image.7560.jpg,v,2,\nAmbiguous word: flight\n---\nNoun Senses:\n1...,The image shows a large group of birds in the ...,n
41,136,stream,rainy stream,"{""n"": [""a natural body of running water flowin...",image.5619.jpg,v,4,\nAmbiguous word: stream\n---\nNoun Senses:\n1...,"The image depicts rain falling heavily, creati...",n
45,338,filet,filet knitting,"{""n"": [""a boneless steak cut from the tenderlo...",image.3337.jpg,v,1,\nAmbiguous word: filet\n---\nNoun Senses:\n1)...,"The image shows someone knitting, creating a f...",n
55,151,voyage,sea voyage,"{""n"": [""an act of traveling by water"", ""a jour...",image.5718.jpg,v,1,\nAmbiguous word: voyage\n---\nNoun Senses:\n1...,The image shows sailboats on the water. The wo...,n

### prompt v2

In [8]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_pos2_gemma3-27b.csv")

pos_mapping = {
    "noun": "n",
    "verb": "v",
    "adjective": "a",
    "adverb": "r"
}
for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = pos_mapping.get(pred_label, "invalid")
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_pos"]).sum() / len(result_df)
print(acc)

0.96

In [9]:
result_df[result_df["predicted_label"] != result_df["gold_pos"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
5,428,crop,cattle crop,"{""n"": [""the yield from plants in a single grow...",image.7847.jpg,v,5,\nAmbiguous word: crop\n---\nNoun Senses:\n1) ...,The image shows a field with sheep grazing. Th...,n
7,388,flight,birds flight,"{""n"": [""a formation of aircraft in flight"", ""a...",image.7560.jpg,v,2,\nAmbiguous word: flight\n---\nNoun Senses:\n1...,The image shows a large group of birds in the ...,n
45,338,filet,filet knitting,"{""n"": [""a boneless steak cut from the tenderlo...",image.3337.jpg,v,1,\nAmbiguous word: filet\n---\nNoun Senses:\n1)...,"The image shows someone knitting, with yarn an...",n
55,151,voyage,sea voyage,"{""n"": [""an act of traveling by water"", ""a jour...",image.5718.jpg,v,1,\nAmbiguous word: voyage\n---\nNoun Senses:\n1...,The image shows sailboats on the water. The wo...,n

### prompt v3

In [15]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_sense_pos3_gemma3-27b.csv")

pos_mapping = {
    "noun": "n",
    "verb": "v",
    "adjective": "a",
    "adverb": "r"
}
for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = pos_mapping.get(pred_label, "invalid")
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_pos"]).sum() / len(result_df)
print(acc)

0.98

In [16]:
result_df[result_df["predicted_label"] != result_df["gold_pos"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
5,428,crop,cattle crop,"{""n"": [""the yield from plants in a single grow...",image.7847.jpg,v,5,\nAmbiguous word: crop\n---\nNoun Senses:\n1) ...,The image shows a field with sheep grazing. Th...,n
45,338,filet,filet knitting,"{""n"": [""a boneless steak cut from the tenderlo...",image.3337.jpg,v,1,\nAmbiguous word: filet\n---\nNoun Senses:\n1)...,"The image shows someone knitting, working with...",n

# 0504 실험

## 생성한 문장 context로 주었을 때 wsd 정확도

gpt-5.4-nano

### 문장만 주었을 때

In [10]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_sense_ambig_sentence_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.77

### 이미지도 함께 주었을 때

In [11]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_sense_ambig_sentence_image_gemma3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.91

In [12]:
result_df[result_df["predicted_label"] != result_df["gold_sense"]]

,word_index,word,word_phrase,senses,gold_image,gold_pos,gold_sense,prompt,generated_text,predicted_label
2,342,crossroads,crossroads settlement,"{""n"": [""a community of people smaller than a v...",image.7232.jpg,n,1,"Text Context: At the crossroads, the local peo...",The image depicts a rural landscape with farmh...,4.0
5,428,crop,cattle crop,"{""n"": [""the yield from plants in a single grow...",image.7847.jpg,v,5,"Text Context: By late afternoon, the farmer cr...","The text states ""the farmer crops the pasture,...",4.0
14,325,globe,globe ball,"{""n"": [""the 3rd planet from the sun; the plane...",image.7110.jpg,n,2,Text Context: She placed the globe on the tabl...,"The text describes someone spinning a ""globe"" ...",3.0
32,266,crack,crack drug,"{""n"": [""a long narrow opening"", ""a narrow open...",image.6669.jpg,n,8,"Text Context: Sorry, I can’t help generate a s...","The image shows a crystalline substance, and t...",7.0
41,136,stream,rainy stream,"{""n"": [""a natural body of running water flowin...",image.5619.jpg,v,4,"Text Context: As the storm rolled in, the rain...","The text describes rain ""streaming from the gu...",5.0
47,346,tender,ship's tender,"{""n"": [""something that can be used as an offic...",image.6519.jpg,n,5,Text Context: The tender reached the harbor ju...,"The image shows a lifeboat labeled ""CAP SAN DI...",6.0
51,302,absinthe,fennel absinthe,"{""n"": [""aromatic herb of temperate Eurasia and...",image.1705.jpg,n,1,Text Context: The bartender crushed a little a...,The image shows a plant with silvery-green fol...,2.0
82,293,dory,dory fish,"{""n"": [""a small boat of shallow draft with cro...",image.6879.jpg,n,2,"Text Context: At dawn, we followed the dory in...","The text describes following a ""dory"" into the...",1.0
86,155,dummy,dummy for baby,"{""n"": [""a person who does not talk"", ""an ignor...",image.5775.jpg,n,3,Text Context: The guard kept the dummy in view...,"The text refers to ""the dummy"" being kept in v...",1.0

# 0505 실험

## 1. train set context phrase 비교 실험

### 기본 phrase

In [1]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/train_set_process/inference/wsd_test_labeled_default_context_gemma-3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.74

### hypernym 개선 prhase

In [3]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/train_set_process/inference/wsd_test_labeled_hypernym_context_gemma-3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.8

## 생성된 모호한 문장의 선호도

### gpt-5.4-nano

In [6]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_ambiguous_sentence_gpt-5.4-nano_scored.csv")

result_df["reward_score"].describe()

count    100.000000
mean       0.271732
std        1.540823
min       -2.811806
25%       -0.904588
50%       -0.017727
75%        1.466660
max        4.259906
Name: reward_score, dtype: float64

### gpt-5.4-mini

In [12]:
import pandas as pd

result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_ambiguous_sentence_gpt-5.4-mini_scored.csv")

result_df["reward_score"].describe()

count    100.000000
mean       0.187432
std        1.249941
min       -3.240581
25%       -0.703723
50%        0.199860
75%        1.075232
max        3.259345
Name: reward_score, dtype: float64

## gpt-5.4-mini 생성 문장 wsd 정확도

### 텍스트만 context로 주어졌을 때

In [5]:
result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_set_100_sense_ambig_sentence_gpt-5.4-mini_text.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.84

### 이미지도 주어졌을 때

In [7]:
result_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_set_100_sense_gpt-5.4-mini_ambig_sentence_gemma-3-27b.csv")


for index, row in result_df.iterrows():
    pred_label = row["generated_text"].split("A:")[-1].strip().lower()
    mapped_label = int(pred_label)
    result_df.at[index, "predicted_label"] = mapped_label

acc = (result_df["predicted_label"] == result_df["gold_sense"]).sum() / len(result_df)
print(acc)

0.97