In [1]:
import pandas as pd
import random

## 단어 sense 리스트 얻기

In [2]:
from nltk.corpus import wordnet as wn

In [19]:
word = "bank"

word_senses = wn.synsets(word)

sense_list = list()
for sense in word_senses:
    sense_list.append(sense.definition())

In [25]:
# 두 sense 비교하기
print(sense_list[5])
print(sense_list[13])

the funds held by a gambling house or the dealer in some gambling games
act as the banker in a game or in gambling

# 정답 sense 달기

In [27]:
import json

In [77]:
# caption csv 파일 읽기

caption_df = pd.read_csv("/workspace/data/captioned_polysemy_words_sense_filtered.csv")

In [39]:
def print_annotation_info(df_row):
    # caption의 sense annotation에 필요한 정보를 출력한다.
    print(f"Interested word: {df_row['word']}")
    sense_dict = json.loads(df_row["senses"])
    for i, sense in enumerate(sense_dict["senses"]):
        print(f"{chr(97 + i)}) {sense}") # 'a', 'b', 'c' 형태로 sense 출력
    
    print(f"Caption: {df_row['generated_caption']}")

In [42]:
answer_list = list()

In [40]:
# index 0
print_annotation_info(caption_df.iloc[0])

Interested word: andromeda
a) broad-leaved evergreen Asiatic shrub with glossy leaves and drooping clusters of white flowers
b) (Greek mythology) an Ethiopian princess and daughter of Cassiopeia; she was fastened to a rock and exposed to a sea monster that was sent by Poseidon, but she was rescued by Perseus and became his wife
c) a constellation in the northern hemisphere between Cassiopeia and Pegasus; contains the Andromeda galaxy
Caption: The delicate, bell-shaped flowers cascade from the branches of the evergreen shrub known as andromeda.

In [43]:
# answer: a
answer_list.append("a")

In [46]:
# index 1
print_annotation_info(caption_df.iloc[1])

Interested word: bank
a) sloping land (especially the slope beside a body of water)
b) a financial institution that accepts deposits and channels the money into lending activities
c) an arrangement of similar objects in a row or in tiers
d) a supply or stock held in reserve for future use (especially in emergencies)
e) the funds held by a gambling house or the dealer in some gambling games
f) a slope in the turn of a road or track; the outside is higher than the inside in order to reduce the effects of centrifugal force
g) a container (usually with a slot in the top) for keeping money at home
h) tip laterally
Caption: The river flows gently through the canyon, its waters lapping against the rocky bank.

In [47]:
# answer: a
answer_list.append("a")

In [48]:
# index 2
print_annotation_info(caption_df.iloc[2])

Interested word: router
a) a worker who routes shipments for distribution and delivery
b) (computer science) a device that forwards data packets between computer networks
c) a power tool with a shaped cutter; used in carpentry for cutting grooves
Caption: This device is a router with several Ethernet ports for connecting wired devices.

In [49]:
# answer: b
answer_list.append("b")

In [51]:
# index 3
print_annotation_info(caption_df.iloc[3])

Interested word: stick
a) an implement consisting of a length of wood
b) a small thin branch of a tree
c) a lever used by a pilot to control the ailerons and elevators of an airplane
d) a rectangular quarter pound block of butter or margarine
e) informal terms for the leg
f) a long implement (usually made of wood) that is shaped so that hockey or polo players can hit a puck or ball
g) a long thin implement resembling a length of wood
h) marijuana leaves rolled into a cigarette for smoking
i) threat of a penalty
Caption: This classic black controller features a prominent stick for navigating games.

In [52]:
# answer: g
answer_list.append("g")

In [54]:
# index 4
print_annotation_info(caption_df.iloc[4])

Interested word: swing
a) a state of steady vigorous action that is characteristic of an activity
b) mechanical device used as a plaything to support someone swinging back and forth
c) a sweeping blow or stroke
d) a style of jazz played by big bands popular in the 1930s; flowing rhythms but less complex than later styles of jazz
e) a jaunty rhythm in music
f) the act of swinging a golf club at a golf ball and (usually) hitting it
g) in baseball; a batter's attempt to hit a pitched ball
h) a square dance figure; a pair of dancers join hands and dance around a point between them
Caption: The batsman takes a wide swing at the cricket ball as he defends his wicket.

In [55]:
# answer: c
answer_list.append("c")

In [57]:
# index 5
print_annotation_info(caption_df.iloc[5])

Interested word: tube
a) conduit consisting of a long hollow object (usually cylindrical) used to hold and conduct objects or liquids or gases
b) electronic device consisting of a system of electrodes arranged in an evacuated glass or metal envelope
c) a hollow cylindrical shape
d) (anatomy) any hollow cylindrical body structure
e) an electric railway operating below the surface of the ground (usually in a city)
Caption: The dark tunnel shows a complex network of tracks within the city's tube.

In [58]:
# answer: e
answer_list.append("e")

In [60]:
# index 6
print_annotation_info(caption_df.iloc[6])

Interested word: venus
a) the second nearest planet to the sun; it is peculiar in that its rotation is slow and retrograde (in the opposite sense of the Earth and all other planets except Uranus); it is visible from Earth as an early `morning star' or an `evening star'
b) goddess of love; counterpart of Greek Aphrodite
c) type genus of the family Veneridae: genus of edible clams with thick oval shells
Caption: The swirling cloud patterns obscure the surface of venus, giving the planet a hazy, golden appearance.

In [61]:
# answer: a
answer_list.append("a")

In [63]:
# index 7
print_annotation_info(caption_df.iloc[7])

Interested word: wheel
a) a simple machine consisting of a circular frame with spokes (or a solid disc) that can rotate on a shaft or axle (as in vehicles or other machines)
b) a handwheel that is used for steering
c) forces that provide energy and direction
d) a circular helm to control the rudder of a vessel
e) game equipment consisting of a wheel with slots that is used for gambling; the wheel rotates horizontally and players bet on which slot the roulette ball will stop in
f) an instrument of torture that stretches or disjoints or mutilates victims
g) a wheeled vehicle that has two wheels and is moved by foot pedals
Caption: A decorative wall display features a series of stacked wooden shelves alongside a large, rustic wagon wheel.

In [64]:
# answer: a
answer_list.append("a")

In [66]:
# index 8
print_annotation_info(caption_df.iloc[8])

Interested word: white
a) a member of the Caucasoid race
b) the quality or state of the achromatic color of greatest lightness (bearing the least resemblance to black)
c) a tributary of the Mississippi River that flows southeastward through northern Arkansas and southern Missouri
d) the white part of an egg; the nutritive and protective gelatinous substance surrounding the yolk consisting mainly of albumin dissolved in water
e) (board games) the lighter pieces
f) (usually in the plural) trousers made of flannel or gabardine or tweed or white cloth
Caption: The egg yolk sits nestled within the clear, translucent white of the egg.

In [67]:
# answer: d
answer_list.append("d")

In [68]:
# index 9
print_annotation_info(caption_df.iloc[9])

Interested word: acrobatics
a) the gymnastic moves of an acrobat
b) the performance of stunts while in flight in an aircraft
Caption: The vintage aircraft performs impressive acrobatics against a clear blue sky.

In [69]:
# answer: b
answer_list.append("b")

In [70]:
# index 10
print_annotation_info(caption_df.iloc[10])

Interested word: adalia
a) a port city in southwestern Turkey on the Gulf of Antalya
b) genus of ladybugs
Caption: A lovely adalia rests peacefully on a textured leaf.

In [71]:
# answer: b
answer_list.append("b")

In [72]:
# index 11
print_annotation_info(caption_df.iloc[11])

Interested word: administration
a) a method of tending to or managing the affairs of a some group of people (especially the group's business affairs)
b) the persons (or committees or departments etc.) who make up a body for the purpose of administering something
c) the act of administering medication
d) the tenure of a president
e) the act of governing; exercising authority
f) the act of meting out justice according to the law
Caption: A group of officials pose for a photo in a factory setting, likely during a tour of the facility with the local administration.

In [73]:
# answer: b
answer_list.append("b")

In [78]:
# index 12
print_annotation_info(caption_df.iloc[12])

Interested word: amber
a) a deep yellow color
b) a hard yellowish to brownish translucent fossil resin; used for jewelry
Caption: This beautiful specimen showcases the warm, golden hues of amber, a fossilized tree resin.

In [79]:
# answer: b
answer_list.append("b")

## current place

In [80]:
# index 13
print_annotation_info(caption_df.iloc[13])

Interested word: ambrosia
a) a mixture of nectar and pollen prepared by worker bees and fed to larvae
b) any of numerous chiefly North American weedy plants constituting the genus Ambrosia that produce highly allergenic pollen responsible for much hay fever and asthma
c) fruit dessert made of oranges and bananas with shredded coconut
d) (classical mythology) the food and drink of the gods; mortals who ate it became immortal
Caption: This colorful dessert salad looks like a delightful bowl of fruit-filled ambrosia.

In [81]:
# answer: c
answer_list.append("c")

## DataFrame에 정답 추가하고 저장

In [82]:
caption_df["gold_answer"] = answer_list

caption_df.to_csv("/workspace/data/captioned_polysemy_words_sense_filtered_with_gold_answer.csv", index=False)

# 데이터셋 구축 자동화를 위한 셋 구축

In [24]:
entire_df = pd.read_csv("/workspace/data/train_set_process/wsd_set_entire.csv")
labeled_df = pd.read_csv("/workspace/data/train_set_process/wsd_set_n500.csv")

In [4]:
entire_df

,word_index,word,senses,gold_image
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg
1,11,upset,"{""noun_senses"": [""an unhappy and worried menta...",image.185.jpg
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg
...,...,...,...,...
3259,12832,teacake,"{""noun_senses"": [""flat semisweet cookie or bis...",image.6412.jpg
3260,12837,saccade,"{""noun_senses"": [""a rapid, jerky movement of t...",image.5270.jpg
3261,12844,tug-of-war,"{""noun_senses"": [""any hard struggle between eq...",image.7358.jpg
3262,12849,tax,"{""noun_senses"": [""charge against a citizen's p...",image.1004.jpg
3263,12861,ducking,"{""noun_senses"": [""hunting ducks"", ""the act of ...",image.12919.jpg

In [5]:
labeled_df

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg,1,The moorhen blended well with the surrounding ...
1,11,upset,"{""verb_senses"": [""disturb the balance or stabi...",image.185.jpg,6,The unexpected performance by the rookie is go...
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong..."
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg,3,The craftsman relied on the beater to ensure a...
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg,1,He always enjoyed sprat with a squeeze of lemon.
...,...,...,...,...,...,...
545,2736,nuke,"{""verb_senses"": [""strike at with firepower or ...",image.14260.jpg,2,"After reviewing the options, the crew decided ..."
546,2742,attic,"{""noun_senses"": [""floor consisting of open spa...",image.4755.jpg,1,He spent the entire afternoon focused on the a...
547,2744,fall,"{""verb_senses"": [""descend in free fall under t...",image.14268.jpg,1,The giant will fall before the day is over.
548,2746,overpower,"{""verb_senses"": [""overcome by superior force"",...",image.194.jpg,1,The sudden surge of the crowd began to overpow...
549,2756,shakedown,"{""noun_senses"": [""initial adjustments to impro...",image.2859.jpg,1,The director mentioned that a shakedown was ne...

두 dataframe을 병합한다.

단순 병합은 안 됨

오픈소스 언어 모델의 성능을 검증하고 tuning하기 위한 각 sub task의 레이블이 필요

1. 해당 샘플을 삭제할 것인가.(delete or not)
1. 해당 샘플이 동사 혹은 명사 sense 중 어느 쪽인가. (주어진 이미지로 판단)
1. 식별한 품사의 sense 중에 정답 센스 판단하기

## 훈련 셋 베이스 만들기 (통합하기)

In [25]:
labeled_index = labeled_df["word_index"].tolist()
labeled_index = set(labeled_index)
# 삭제한 샘플은 labeled_df에는 들어있지 않음
# entire_df에서 labeled_df에 들어있지 않은 샘플을 찾아서 labled_df에 추가
# labeled_df에는 ambiguous sentence 열이 있는데 entire_df에는 ambiguous sentence 열이 없다.
# 따라서 ambiguous sentence 열을 일종의 label로 사용할 수 있음.
# 비어있으면 취급 안 하는 sample이라는 레이블이 붙은 것으로 간주

import json
# labeled_df에서 가장 마지막으로 label한 샘플까지만 순회를 진행
last_labeled_index = labeled_df["word_index"].max()
entire_df_labeled = entire_df[entire_df["word_index"] <= last_labeled_index]
for index, row in entire_df_labeled.iterrows():
    if row["word_index"] not in labeled_index:
        new_row = pd.DataFrame({
            "word_index": [row["word_index"]],
            "word": [row["word"]],
            "senses": [row["senses"]],
            "gold_image": [row["gold_image"]],
            "gold_sense": [-1],
            "ambiguous_sentence": [""],
        })
        labeled_df = pd.concat([labeled_df, new_row], ignore_index=True)
    else:
        cur_labeled_row = labeled_df[labeled_df["word_index"] == row["word_index"]]
        sense_dict = json.loads(cur_labeled_row["senses"].iloc[0])
        if "noun_senses" in sense_dict:
            sense_dict["gold_pos"] = "noun"
        elif "verb_senses" in sense_dict:
            sense_dict["gold_pos"] = "verb"
        
        entire_sense_dict = json.loads(row["senses"])
        sense_dict.update(entire_sense_dict)
        
        labeled_df.loc[labeled_df["word_index"] == row["word_index"], "senses"] = json.dumps(sense_dict, ensure_ascii=False)

labeled_df

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg,1,The moorhen blended well with the surrounding ...
1,11,upset,"{""verb_senses"": [""disturb the balance or stabi...",image.185.jpg,6,The unexpected performance by the rookie is go...
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong..."
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg,3,The craftsman relied on the beater to ensure a...
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg,1,He always enjoyed sprat with a squeeze of lemon.
...,...,...,...,...,...,...
713,2647,disagreement,"{""noun_senses"": [""a conflict of people's opini...",image.4661.jpg,-1,
714,2669,chin,"{""noun_senses"": [""the protruding part of the l...",image.9258.jpg,-1,
715,2687,vellum,"{""noun_senses"": [""a heavy creamy-colored paper...",image.3518.jpg,-1,
716,2713,music,"{""noun_senses"": [""an artistic form of auditory...",image.12003.jpg,-1,
717,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,

In [26]:
# labeled_df를 word_index 기준으로 정렬
labeled_df = labeled_df.sort_values(by="word_index").reset_index(drop=True)

labeled_df

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence
0,0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",image.0.jpg,1,The moorhen blended well with the surrounding ...
1,11,upset,"{""verb_senses"": [""disturb the balance or stabi...",image.185.jpg,6,The unexpected performance by the rookie is go...
2,14,breakdown,"{""noun_senses"": [""the act of disrupting an est...",image.239.jpg,3,"After years of relentless pursuit, the prolong..."
3,20,beater,"{""noun_senses"": [""a worker who rouses wild gam...",image.339.jpg,3,The craftsman relied on the beater to ensure a...
4,31,sprat,"{""noun_senses"": [""small fatty European fish; u...",image.516.jpg,1,He always enjoyed sprat with a squeeze of lemon.
...,...,...,...,...,...,...
713,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,
714,2742,attic,"{""noun_senses"": [""floor consisting of open spa...",image.4755.jpg,1,He spent the entire afternoon focused on the a...
715,2744,fall,"{""verb_senses"": [""descend in free fall under t...",image.14268.jpg,1,The giant will fall before the day is over.
716,2746,overpower,"{""verb_senses"": [""overcome by superior force"",...",image.194.jpg,1,The sudden surge of the crowd began to overpow...
717,2756,shakedown,"{""noun_senses"": [""initial adjustments to impro...",image.2859.jpg,1,The director mentioned that a shakedown was ne...

In [27]:
labeled_df.to_csv("/workspace/data/dataset_construction_train/train_set_base.csv", index=False)

### 셋을 무작위로 test와 validation으로 나누기

In [3]:
# 100개를 test set으로 분리
labeled_df = pd.read_csv("/workspace/data/dataset_construction_train/train_set_base.csv")
test_df = labeled_df.sample(n=100, random_state=42)
train_df = labeled_df.drop(test_df.index)
val_df = train_df.sample(n=50, random_state=42)
train_df = train_df.drop(val_df.index)

test_df.to_csv("/workspace/data/dataset_construction_train/test_set.csv", index=False)
val_df.to_csv("/workspace/data/dataset_construction_train/val_set.csv", index=False)
train_df.to_csv("/workspace/data/dataset_construction_train/train_set.csv", index=False)

## 품사 분류 task 수행 과정

캡션은 

1. 주어진 단어에 관해 달기
1. 단어를 주지 않고, 그냥 묘사하게 하기

두 가지로 달 수 있다.

품사 분류 task 학습을 위한 캡션이므로 품사 레이블이 달린 샘플만 취급한다

In [4]:
# base dataframe 열기
base_df = pd.read_csv("/workspace/data/dataset_construction_train/train_set_base.csv")

labeled_df = base_df[base_df["gold_sense"] != -1]

### 프롬프트 1

In [3]:
prompt_template1 = """Given a word and an image, try to explain the image with the given word.
Do not indicate you are captioning an image. Do not mention 'The/This image', 'The/This photograph', etc. Do not highlight the given word in the sentence.
Word: {word}"""

In [6]:
prompt_list = list()
for index, row in labeled_df.iterrows():
    word = row["word"]
    prompt = prompt_template1.format(word=word)
    prompt_list.append(prompt)

labeled_df.loc[labeled_df.index, "prompt"] = prompt_list

In [7]:
labeled_df.to_csv("/workspace/data/dataset_construction_train/train_set_caption_prompt1.csv", index=False)

### 생성한 Caption으로 BERT 학습용 데이터셋 구성

In [25]:
# 생성한 캡션 가져오기
caption_df = pd.read_csv("/workspace/data/dataset_construction_train/inference/caption_prompt1_results_gemma3-27b.csv")

In [26]:
# 무엇이 필요한가?
# BERT에 주기 위한 task description 프롬프트와 classification label이 필요하다.
import json
label_list = list()
for index, row in caption_df.iterrows():
    print(f"{row['word']}")
    senses_dict = json.loads(row["senses"])
    label = senses_dict["gold_pos"]
    if label == "noun":
        label = 0
    elif label == "verb":
        label = 1
    label_list.append(label)

caption_df["label"] = label_list

moorhen
upset
breakdown
beater
sprat
paddle
beech
brisling
patient
student
runner
beatification
enlightenment
pica
subsidence
bottle
ogre
discrimination
yaws
loafer
disa
dagger
schooling
dram
fir
rainbow
drama
insect
bobtail
throw
symbolism
dumbbell
wolverine
ambush
foul
storm
assort
siren
stirrup
treasury
wrath
jet
funfair
slapstick
distributor
drought
cross-stitch
trench
magnolia
distribution
core
eater
puck
volleyball
fistula
shampoo
metre
bitters
scorpion
exhibitionism
crinoline
totalizer
paint
chatterbox
oil
scan
patchouli
waxflower
mazurka
cape
notation
concertina
mechanism
breaker
unit
mixer
cheesecake
reflexion
cross-pollination
mast
equator
beef
beat
being
enjoy
equation
cornice
pine
tailfin
groom
guernsey
porte-cochere
baptists
football
furnishing
porter
volume
bee
behavior
scrubber
buzzer
cone
furring
haw
square
whip
enlighten
grill
ennoblement
bolo
sabre
break
rain
bond
return
spar
profession
overtake
wrench
foundation
haul
strawberry
rosewood
oglala
breadfruit
lecture
speculum
slam
jackfruit
marang
actor
ti
straw
humanities
sweeper
uplift
loaf
founder
mining
harbor
tailspin
butchery
tarragon
cirrus
bar
behemoth
peeler
chariot
cherry
catgut
upholstery
code
mummy
embryo
catfish
butcher
coca
mirage
corruption
bitter
octopus
popcorn
assault
raise
coach
celebrity
hang
desolate
indian
disheartenment
rupee
radius
jewfish
egg
spirits
cairn
quickstep
bank
runway
pack
greet
registration
worship
elderberry
rupture
rubbish
rerun
eagle
girlfriend
galvanization
rotisserie
pile
circus
distortion
back
surprise
train
swash
photometer
jacket
stout
replay
chat
desperation
caterpillar
sunglasses
croup
harmony
trunk
trailer
dyke
compound
trifle
musk
cater
sylph
server
cornerstone
urn
cohesion
corrosion
conducting
macaroni
hand
truck
whistle
vitriol
arnica
cod
quoin
censorship
baritone
caisson
galaxy
entree
corner
cordoba
set
grind
last
galley
cobbler
jawbreaker
present
merger
drop
property
land
carbonado
waist
brightness
bosom
pop
raphael
liquidambar
radiance
serve
booby
pop-up
lick
bubble
bury
approach
racism
garage
race
scarf
night
crier
segregation
finance
harpy
garambulla
wound
magpie
jingle
airway
duet
liparis
leadership
disobedience
suggestion
duffle
rip
sisal
stock
laver
slate
crying
famine
daub
distillation
irrigate
apheresis
correspondent
keyboard
indicator
jacks
adder
waiter
deactivation
gallery
wait
fan
automaton
muskmelon
trainer
cable
shock
transmission
spinet
mackintosh
sew
miscarriage
cuckoo
conga
condominium
broadside
forehead
gear
evaporate
macadam
epitaph
treacle
packrat
bronze
gastronomy
gargoyle
worm
confront
throstle
hardware
waders
escudo
attack
call
wafer
monitor
mist
blow
spatula
snapper
clove
bride
forward
confuse
communication
war
pompano
retrain
ration
tuner
stamp
screen
prostration
ecology
retraction
stab
cookie
promotion
fatality
pump
biscuit
knight
asphalt
bully
strap
hoof
amaranth
wad
taenia
rye
yen
strike
goose
armilla
ruler
blusher
vinegar
iceman
dishwasher
touch
ticking
shepherd
lizard
end
troll
dish
knife
hive
thresh
tickle
bamboo
haymaking
innocence
disgust
relax
bean
interception
deliver
pengo
complaint
experiment
commune
overstep
citron
desecrate
salsify
testudo
chalk
browse
oyster
design
gate
orchis
listing
mephitis
bushel
fraction
maillot
noise
flirt
pilot
melt
burn
pay
nanny
fossil
assemble
elamite
mystification
load
sadness
specialization
spider
dowse
broccoli
listen
skirt
kiowa
rape
stuff
skate
rutabaga
group
rustling
read
buffalo
cook
residency
spice
draw
democracy
mombin
study
shame
denim
kauri
instrument
tie
disguise
rustication
thrift
sheep
yawl
sing
swordfish
interchange
drum
give
hash
hazel
propitiation
extortion
scream
gallfly
supernumerary
tree
bracer
disappointment
thirst
shadow
haze
screamer
acoustics
beaker
cloud
modernization
mamey
ham
depilation
palette
threaten
garland
meditation
dashboard
vaccination
chrysanthemum
mythology
electrification
competition
indicate
jockey
listlessness
dandruff
citizenship
mamma
electricity
scribe
law
labyrinth
yarn
vanilla
poster
cabbage
brick
calculate
pablum
rave
elevate
cauliflower
dial
dissolution
first
pontoon
mushroom
computer
cabinet
hammer
bake
walnut
gull
insubordination
watchdog
instrumentation
grouper
facade
jaundice
fraud
bolivar
score
flail
waste
garnish
graduate
grip
grasp
stoup
launcher
snow
knock
anvil
grapple
launching
alabama
tamarind
banishment
momentum
jog
dash
taco
refuel
kip
musician
hag
knitting
may
fillet
disposal
chapel
hear
strings
vellum
shelf
pain
mormon
cochineal
nuke
attic
fall
overpower
shakedown

In [27]:
caption_df["label"].value_counts()

label
0    485
1     97
Name: count, dtype: int64

In [28]:
prompt_template = """Caption: {caption}
Word: {word}
Noun senses:
{noun_senses}
Verb senses:
{verb_senses}
---
You are given a caption describing an image, along with a list of words and their noun and verb meanings. Based on all of this information, determine whether the word is used as a verb or a noun in the image."""

In [29]:
import json
for index, row in caption_df.iterrows():
    word = row["word"]
    caption = row["answer"]
    
    sense_dict = json.loads(row["senses"])
    noun_senses = sense_dict["noun_senses"]
    verb_senses = sense_dict["verb_senses"]
    noun_senses_str = "\n".join([f"- {sense}" for sense in noun_senses])
    verb_senses_str = "\n".join([f"- {sense}" for sense in verb_senses])
    prompt = prompt_template.format(caption=caption, word=word, noun_senses=noun_senses_str, verb_senses=verb_senses_str)
    caption_df.loc[index, "prompt"] = prompt

In [ ]:
# 기존에 생성된 캡션은 필요없으니 제거함이 옳다.
caption_df = caption_df.drop(columns=["answer"])
caption_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_base.csv", index=False)

In [31]:
# 완성된 데이터셋을 train, validation, test set으로 분리하기
test_df = caption_df.sample(n=100, random_state=42)
train_df = caption_df.drop(test_df.index)
val_df = train_df.sample(n=50, random_state=42)
train_df = train_df.drop(val_df.index)

test_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_test.csv", index=False)
val_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_val.csv", index=False)
train_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_train.csv", index=False)

In [38]:
prompt2_template = """Caption: {caption}
Word: {word}
Noun senses:
{noun_senses}
Verb senses:
{verb_senses}
---
You are given a caption describing an image, along with a list of words and their noun and verb meanings. Based on all of this information, determine whether the word is used as a verb or a noun in the image. If both pos are applicable, consider the sense list of each pos and choose the one that can be used more diversely in various contexts."""

caption_df = pd.read_csv("/workspace/data/dataset_construction_train/inference/caption_prompt1_results_gemma3-27b.csv")

import json
label_list = list()
for index, row in caption_df.iterrows():
    senses_dict = json.loads(row["senses"])
    label = senses_dict["gold_pos"]
    if label == "noun":
        label = 0
    elif label == "verb":
        label = 1
    label_list.append(label)

caption_df["label"] = label_list

for index, row in caption_df.iterrows():
    word = row["word"]
    caption = row["answer"]
    
    sense_dict = json.loads(row["senses"])
    noun_senses = sense_dict["noun_senses"]
    verb_senses = sense_dict["verb_senses"]
    noun_senses_str = "\n".join([f"- {sense}" for sense in noun_senses])
    verb_senses_str = "\n".join([f"- {sense}" for sense in verb_senses])
    prompt = prompt2_template.format(caption=caption, word=word, noun_senses=noun_senses_str, verb_senses=verb_senses_str)
    caption_df.loc[index, "prompt"] = prompt

# 기존에 생성된 캡션은 필요없으니 제거함이 옳다.
caption_df = caption_df.drop(columns=["answer"])
caption_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_base.csv", index=False)

# 완성된 데이터셋을 train, validation, test set으로 분리하기
test_df = caption_df.sample(n=100, random_state=42)
train_df = caption_df.drop(test_df.index)
val_df = train_df.sample(n=50, random_state=42)
train_df = train_df.drop(val_df.index)

test_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_test_prompt2.csv", index=False)
val_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_val_prompt2.csv", index=False)
train_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_train_prompt2.csv", index=False)

### 데이터셋에서 verb label sample 증강하기

데이터셋이 imbalance한 상태라서 수가 적은 verb label sample을 증강하려 한다.

In [32]:
# train df 불러오기
train_df = pd.read_csv("/workspace/data/dataset_construction_train/pos_tagging_train.csv")

# verb sample 2배수로 증강하기
verb_df = train_df[train_df["label"] == 1]
train_df = pd.concat([train_df, verb_df], ignore_index=True)
train_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_train_augmentedx2.csv", index=False)

In [39]:
# train df 불러오기
train_df = pd.read_csv("/workspace/data/dataset_construction_train/pos_tagging_train_prompt2.csv")

# verb sample 2배수로 증강하기
verb_df = train_df[train_df["label"] == 1]
train_df = pd.concat([train_df, verb_df], ignore_index=True)
train_df.to_csv("/workspace/data/dataset_construction_train/pos_tagging_train_prompt2_augmentedx2.csv", index=False)

### LLM zero-shot 품사 분류 수행을 위한 prompt 템플릿 마련

In [1]:
prompt_template="""
Ambiguous word: {word}
---
Noun senses:
{noun_senses}
---
Verb senses:
{verb_senses}
---
Adjective senses:
{adj_senses}
---
Adverb senses:
{adv_senses}
---
You are an expert linguistic annotator. Image, a specific target word found within the context of that image, and a list of potential senses for that word are given. Each sense is categorized by a Part of Speech (POS): noun, verb, adjective, or adverb.

Your goal is to determine the correct POS by selecting the sense that most directly aligns with the visual context.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

Directness of Meaning: Choose the sense that provides the most direct and specific fit for the visual context. Even if a perfect match does not exist, select the sense that is the closest indirect match.

The "Verb" Action Rule: Assign the Verb POS if the image depicts a person or entity performing the action. A word can be classified as a Verb even if no humans are present, provided the image illustrates the active manifestation or "happening" of that sense.

Crucial Exception: Choose POS of the sense that provides a more direct, varied, or dynamic description of the image than other senses, prioritize the POS.

---
After all your reasoning is finished, provide your final decision as the format 'A: [POS]', where [POS] is your chosen Part of Speech (noun, verb, adjective, or adverb).
"""

In [4]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/set_process/wsd_set_test_labeled.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    noun_senses = sense_dict.get("n", [])
    verb_senses = sense_dict.get("v", [])
    adj_senses = sense_dict.get("a", [])
    adv_senses = sense_dict.get("r", [])
    prompt = prompt_template.format(
        word=row["word"],
        noun_senses="\n".join([f"- {sense}" for sense in noun_senses]),
        verb_senses="\n".join([f"- {sense}" for sense in verb_senses]),
        adj_senses="\n".join([f"- {sense}" for sense in adj_senses]),
        adv_senses="\n".join([f"- {sense}" for sense in adv_senses]),
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/set_process/wsd_set_test_pos_prompt2.csv", index=False)

## Sense Labeling task 수행

### zero-shot

In [11]:
prompt_template="""Text Context: {context}
Ambiguous Word: {word}
---
Sense List:
{sense_list}
---
You are an expert linguistic annotator. A specific target word found within the context of a given text, and a list of potential senses for that word are provided. Your task is to determine the correct sense by selecting the one that most directly aligns with the context and its background event.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

Directness of Meaning: Choose the sense that provides the most direct and specific fit for the visual and linguistic context. Even if a perfect match does not exist, select the sense that is the closest indirect match.

Focus on entire context: Consider the entire context of the image, not just the immediate appearance or a specific detail. The correct sense may be indicated by those background elements.
---
After all your reasoning is finished, provide your final decision as the format 'A: [sense number]', where [sense number] is the index of your chosen sense from the provided list.
"""

In [12]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/set_process/wsd_set_test_labeled.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    prompt = prompt_template.format(
        word=row["word"],
        context=row["word_phrase"],
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/set_process/wsd_set_test_sense_prompt.csv", index=False)

### Image 검색 문서 이용

#### sub task 1: 상위 문서 k개의 요약문 얻어오기

In [1]:
import trafilatura

def extract_clean_text(url):
    downloaded = trafilatura.fetch_url(url)
    if downloaded:
        # 본문만 추출 (광고, 네비게이션 자동 제거)
        result = trafilatura.extract(downloaded, include_comments=False, include_tables=True)
        return result
    return ""

In [14]:
result = extract_clean_text("https://commons.wikimedia.org/wiki/Gallinula")

In [15]:
result

"Gallinula\nAppearance\nIOC Classification: Domain: Eukaryota • Regnum: Animalia • Phylum: Chordata • Cladus: Reptilia • Cladus: Archosauria • Classis: Aves • Superordo: Neognathae • Ordo: Gruiformes • Familia: Rallidae • Genus: Gallinula Brisson, 1760\nWikispecies has an entry on:\n- English: Moorhens\n- Deutsch: Teichrallen\n- español: Pollas de agua\n- lietuvių: Nendrinės vištelės\n- G. chloropus, G. comeri, G. galeata, †G. nesiotis, †G. pacifica, G. silvestris, G. tenebrosa\n- Note: two species that were placed here in IOC classification 5.4 have been moved to genera Paragallinula, Porphyriops as species Paragallinula angulata, Porphyriops melanops\ngenus of birds | |||||||||||||||||||||||||||||\n| Upload media | |||||||||||||||||||||||||||||\n| Instance of | |||||||||||||||||||||||||||||\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| Subclass of | |||||||||||||||||||||||||||||\n| |||||||||||||||||||||||||||||\n| |||||||||||||||||||||||||||||\n| Taxon author | Mathurin Jacques Brisson, 1760 | ||||||||||||||||||||||||||||\n| |||||||||||||||||||||||||||||\n- Afrikaans: Grootwaterhoender\n- العربية: دجاجة الماء خضراء الأقدام\n- Asturianu: gallineta\n- Brezhoneg: Douryar voutin\n- Català: polla d'aigua comuna\n- Čeština: slípka zelenonohá\n- Cymraeg: iâr ddŵr\n- Dansk: Rørhøne (Grønbenet)\n- Deutsch: Teichhuhn\n- English: Common Moorhen\n- Español: Gallineta común\n- Eesti: tait\n- Suomi: liejukana\n- Français: Gallinule poule-d'eau\n- Gaeilge: Cearc uisce\n- Gàidhlig: Cearc-uisge\n- Gaelg: Kiark ushtey\n- Hrvatski: mlakuša\n- Magyar: vízityúk\n- Bahasa Indonesia: Mandar batu\n- Íslenska: Sefhæna\n- Italiano: Gallinella d'acqua\n- 日本語: バン\n- 한국어: 쇠물닭\n- Kernowek: Lagyar\n- Lietuvių: nendrinė vištelė\n- Latviešu: ūdensvistiņa\n- Malagasy: Aretaka\n- Norsk bokmål: Sivhøne\n- Nederlands: waterhoen\n- Polski: kokoszka (zwyczajna)\n- Português: galinha-de-água-comum\n- Русский: Камышница\n- Davvisámegiella: Láttovuonccis\n- Slovenčina: sliepočka vodná\n- Slovenščina: zelenonoga tukalica\n- Svenska: rörhöna\n- ไทย: นกอีล้ำ\n- Tagalog: uwis\n- Українська: курочка водяна\n- 中文: 黑水鸡\n- Català: polla de l'illa Gough\n- Čeština: slípka goughská\n- Dansk: Goughrørhøne\n- Deutsch: Goughteichhuhn\n- English: Gough Moorhen\n- Español: Gallineta de Gough\n- Eesti: gough'i tait\n- Français: Gallinule de Gough\n- Hrvatski: velika mlakuša\n- Magyar: gough-szigeti vízityúk\n- Italiano: Gallinella di Gough\n- Nederlands: Goughwaterhoen\n- Polski: kokoszka południowa\n- Português: galinha-de-água-da-gonçalo-álvares\n- Русский: Гофская камышница\n- Slovenčina: sliepočka krátkokrídla\n- Svenska: goughrörhöna\n- Català: Polla d'aigua americana\n- Deutsch: Amerikateichhuhn\n- English: Common Gallinule\n- Español: Gallineta americana\n- Suomi: amerikanliejukana\n- Français: Gallinule d’Amérique\n- Gaeilge: Cearc uisce Meiriceánach\n- Avañe'ẽ: Ñahana\n- Hawaiʻi: 'Alae 'ula\n- Hrvatski: američka mlakuša\n- Italiano: Gallinella americana\n- Norsk bokmål: Amerikasivhøne\n- Nederlands: Amerikaans Waterhoen\n- Polski: kokoszka amerykańska\n- Português: galinha-de-água-americana\n- Русский: Американская камышница\n- Slovenčina: sliepočka nahana\n- Svenska: amerikansk rörhöna\n- 中文: 黑水鸡\n-\nGallinula galeata cachinnans\n-\nGallinula galeata sandvicensis\n-\nGallinula galeata sandvicensis\n† Gallinula nesiotis (cat.)\n[edit]- Afrikaans: Gough-eilandwaterhoender\n- Català: polla de Tristan da Cunha\n- Čeština: slípka tristanská\n- Cymraeg: iâr ddŵr Ynys Gough\n- Dansk: Tristanrørhøne\n- Deutsch: Tristan-Inselralle\n- English: Tristan Gallinule\n- Esperanto: Tristana galinolo\n- Español: Gallineta de Tristán de Acuña\n- Eesti: tristan da cunha tait\n- Suomi: etelänliejukana\n- Français: Gallinule de Tristan da Cunha\n- Hrvatski: tristanska mlakuša\n- Magyar: Trisdan da Cunha vízityúk\n- Italiano: Gallinella di Tristan da Cunha\n- 日本語: トリスタンバン\n- Lietuvių: Tristano da Kunjos salyno vištelė\n- Norsk bokmål: Tussoksivhøne\n- Nederlands: Tristanwaterhoen\n- Polski: kokoszka atlantycka\n- Português: galinha-de-água-da-tristão-da-cunha\n- Русский: Тристанская камышница\n- Slovenčina: sliepočka tristanská\n- Svenska: tristanrörhöna\n- Українська: курочка тристанська\n† Gallinula pacifica (cat.)\n[edit]- Català: polla de Samoa\n- Čeština: slípka samojská\n- Cymraeg: iâr ddŵr Samoa\n- Dansk: Samoarørhøne\n- Deutsch: Samoateichhuhn\n- English: Samoan Wood Rail\n- Español: Gallineta de Samoa\n- Eesti: samoa metstait\n- Suomi: samoanliejukana\n- Français: Gallinule punaé\n- Hrvatski: samoanska mlakuša\n- Magyar: szamoai vízityúk\n- Italiano: Gallinella delle Samoa\n- 日本語: サモアオグロバン\n- Lietuvių: Samoa miškinė vištelė\n- Norsk bokmål: Samoasivhøne\n- Nederlands: Samoawaterhoen\n- Polski: kokoszka żółtodzioba\n- Português: galinha-de-água-da-samoa\n- Русский: Самоанская камышница\n- Slovenčina: sliepočka žltočelá\n- Slovenščina: samojska tukalica\n- Svenska: samoarörhöna\n- Українська: курочка самоанська\n- 中文: 薩摩亞水雞\n- Català: polla de l'illa San Cristóbal\n- Čeština: slípka šalomounská\n- Dansk: Makirarørhøne\n- Deutsch: Blaustirn-Teichhuhn\n- English: Makira Moorhen\n- Español: Gallineta de San Cristóbal\n- Eesti: makira metstait\n- Suomi: salomoninliejukana\n- Français: Gallinule d’Edith\n- Hrvatski: solomonska mlakuša\n- Magyar: San Cristobal vízityúk\n- Italiano: Gallinella di San Cristobal\n- 日本語: サンクリストバルオグロバン\n- Lietuvių: sankristobalinė vištelė\n- Norsk bokmål: Skogsivhøne\n- Nederlands: Makirawaterhoen\n- Polski: kokoszka czerwonodzioba\n- Português: galinha-de-água-de-makira\n- Русский: Лесная камышница\n- Slovenčina: sliepočka modročelá\n- Slovenščina: sankristobalska tukalica\n- Svenska: makirarörhöna\n- Українська: курочка синьолоба\n- 中文: 馬基拉水雞\n- Català: polla endolada\n- Čeština: slípka tmavá\n- Cymraeg: iâr ddŵr dywyll\n- Dansk: Mørk Rørhøne\n- Deutsch: Papuateichhuhn\n- English: Dusky Moorhen\n- Esperanto: Sombra galinolo\n- Español: Gallineta enlutada\n- Eesti: tumetait\n- Suomi: tummaliejukana\n- Français: Gallinule sombre\n- Hrvatski: mrka mlakuša\n- Magyar: pápua vízityúk\n- Bahasa Indonesia: Mandar kelam\n- Italiano: Gallinella fosca\n- 日本語: ネッタイバン\n- Lietuvių: tamsioji vištelė\n- Norsk bokmål: Australsivhøne\n- Nederlands: Zwart Waterhoen\n- Polski: kokoszka ciemna\n- Português: galinha-de-água-enlutada\n- Русский: Тёмная камышница\n- Slovenčina: sliepočka tmavá\n- Svenska: mörk rörhöna\n- Українська: курочка чорна\n-\nGallinula tenebrosa frontata, Amaurornis isabellina"

In [7]:
prompt_template="""Ambiguous word: {word}
Entites in Image: 
{entities}
---
You are a linguistic expert. Given a specific target word and 'Entities in Image', your task is to extract and summarize any relevant and helpful information from the given 'Searched Web Content' that can help explain the image. Do not try to describe the image itself if there is no relevant information in the context that can be applied to the image or the 'Entities in Image'. Do not mention the information that is not relevant to the content of the image.
---
Searched Web Content:
- Title: {web_title}
- {text_context}
---
First, Refer to the 'Entities in Image' section to understand the content of the image. Then, read the 'Searched Web Content' section carefully and judge whether it is related to the 'Entities in Image'. Ignore any information that is not relevant to the 'Entities in Image'.
Provide your final answer as a paragraph. The Paragraph should be concise and contain only the essential information.
"""

In [8]:
import json
import pandas as pd
from tqdm.auto import tqdm
# 기존에 retrive하여 저장해놓은 목록에서 test 셋에 해당하는 100개 내역 얻어오기
wsd_test_df = pd.read_csv("/workspace/data/set_process/wsd_set_test_labeled.csv")

# k =3
# 요약은 한 번의 LLM 호출로 하나의 인터넷 문서만 처리하도록 구조 적용
retrieval_df = pd.read_csv("/workspace/data/set_process/wsd_set_entire_google_vision_result.csv")

df_dict = {
    "word_index": [],
    "word": [],
    "word_phrase": [],
    "senses": [],
    "gold_image": [],
    "gold_pos": [],
    "gold_sense": [],
    "prompt": []
}
for index, row in tqdm(wsd_test_df.iterrows(), total=len(wsd_test_df)):
    word_index = row["word_index"]
    retrieved_rows = retrieval_df[retrieval_df["word_index"] == word_index]
    retrieved_urls = json.loads(retrieved_rows["web_urls"].iloc[0])
    retrieved_entities = json.loads(retrieved_rows["entities"].iloc[0])
    if len(retrieved_entities) > 0:
        valid_entites = [retrieved_entities[0]["description"]]
        for entity in retrieved_entities[1:]:
            if entity["score"] >= 1.0:
                valid_entites.append(entity["description"])
        valid_entites = "\n".join([f"- {entity}" for entity in valid_entites])
    else:
        valid_entites = ""
    
    retrieved_urls_num = 0
    url_idx = 0
    none_page_titles = list()
    while url_idx < len(retrieved_urls) and retrieved_urls_num < 3:
        cur_url = retrieved_urls[url_idx]["url"]
        cur_title = retrieved_urls[url_idx]["title"]
        if "www.youtube.com" in cur_url:
            web_content = None
        else:
            web_content = extract_clean_text(cur_url)
        
        if web_content is not None:
            web_content_split = web_content.split('\n')
                
            web_content_list = list()
            cur_content = ""
            content_threshold = 4096
            for line in web_content_split:
                if line.strip() != "":
                    cur_content += line.strip() + "\n"
                if len(cur_content) > content_threshold:
                    web_content_list.append(cur_content)
                    cur_content = ""
                
            if len(cur_content) > 0:
                web_content_list.append(cur_content)
                
            for content in web_content_list:
                df_dict["word_index"].append(word_index)
                df_dict["word"].append(row["word"])
                df_dict["word_phrase"].append(row["word_phrase"])
                df_dict["senses"].append(row["senses"])
                df_dict["gold_image"].append(row["gold_image"])
                df_dict["gold_pos"].append(row["gold_pos"])
                df_dict["gold_sense"].append(row["gold_sense"])
                df_dict["prompt"].append(prompt_template.format(word=row["word"], entities=valid_entites, web_title=cur_title, text_context=content))
            retrieved_urls_num += 1
        else:
            none_page_titles.append(cur_title)
        url_idx += 1
    
    # 마지막으로 3개 추가하는 동안 등장한 None 페이지 제목들을 한꺼번에 요약하도록 프롬프트 생성
    if len(none_page_titles) > 0:
        none_page_titles_str = "\n".join([f"- {title}" for title in none_page_titles])
        df_dict["word_index"].append(word_index)
        df_dict["word"].append(row["word"])
        df_dict["word_phrase"].append(row["word_phrase"])
        df_dict["senses"].append(row["senses"])
        df_dict["gold_image"].append(row["gold_image"])
        df_dict["gold_pos"].append(row["gold_pos"])
        df_dict["gold_sense"].append(row["gold_sense"])
        df_dict["prompt"].append(prompt_template.format(word=row["word"], entities=valid_entites, web_title="etc.", text_context=none_page_titles_str))
    
inference_df = pd.DataFrame(df_dict)
inference_df.to_csv("/workspace/data/set_process/wsd_test_summarize_prompt3.csv", index=False)

100%|██████████| 100/100 [08:22<00:00,  5.02s/it]

#### sub task 2: 요약한 내용을 이용하여 sense labeling 수행

In [9]:
prompt_template="""Text Context: {context}
Ambiguous Word: {word}
---
Sense List:
{sense_list}
---
Image Web Search Results:
{web_search_results}
---
You are an expert linguistic annotator. A specific target word found within the context of a given text, and a list of potential senses for that word are provided. Your task is to determine the correct sense by selecting the one that most directly aligns with the context and its background event.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

First, Use web search results to determine whether there is any background information associated with the given image that cannot be discerned solely from its visual elements. If such information exists, prioritize the sense that best fits this background information, even if it is not the most direct match for the visual content.

Directness of Meaning: If no additional background information can be obtained from the web search results, choose the sense that provides the most direct and specific fit for the visual and linguistic context. Even if a perfect match does not exist, select the sense that is the closest indirect match.
---
After all your reasoning is finished, provide your final decision as the format 'A: [sense number]' and end your generation. In here, [sense number] is the index of your chosen sense from the provided list.
"""

In [10]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/set_process/wsd_set_test_labeled.csv")
web_search_df = pd.read_csv("/workspace/data/set_process/inference/wsd_test_summarize3_gemma3-27b.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    web_search_results = web_search_df.loc[web_search_df["word"] == row["word"], "generated_text"].tolist()
    
    cropped_web_search_results = ""
    crop_threshold = 3000
    while len(cropped_web_search_results) < crop_threshold and len(web_search_results) > 0:
        next_result = web_search_results.pop(0).strip()
        if next_result != "":
            cropped_web_search_results += (next_result + "\n")
    
    prompt = prompt_template.format(
        word=row["word"],
        context=row["word_phrase"],
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
        web_search_results=cropped_web_search_results
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/set_process/wsd_set_test_sense_search_prompt3.csv", index=False)

## 각 프롬프트 별 LM 훈련용 셋 만들기

### 샘플이 valid인지 invalid인지 판별하는 데이터셋

In [3]:
rule1_word_list = ["driftfish", "rosinweed", "arum", "cisco", "quahaug", "linebacker", "discovery", "handicraft", "symphony", "bristle", "cathedral", "infanticide", "mirror", "distraction", "decapitation", "happening", "yolk", "growling", "happiness", "hostility", "misanthropy", "harassment", "amnesty", "entr'acte", "miracle", "sculpt", "belligerence", "bulimia", "worsted", "renting", "news", "bugbane", "hogfish", "amputation", "scatology", "vaishnavism", "mahayana", "belligerency", "armyworm", "pacifism", "mildew", "speleology", "milkweed", "nightlife", "roe", "footwear", "crooning", "hasidism", "pekingese", "divination", "paprikas", "pigweed", "whey", "dream", "kindness", "prove", "cottonwood", "ninja", "flagellant", "candelilla", "brainwashing", "crochet", "mistletoe", "cockle", "solid", "tetanus", "hound's-tongue", "hoof", "spicebush", "explain", "experience", "gudgeon", "skittles", "yankee", "genealogy", "smile", "triclinium", "langouste", "thrips", "crayfish", "endeavor", "beefwood", "redberry", "citrange", "uxoricide", "wallflower", "autograph", "scholasticism", "disagreement", "music", "lithography"]
rule2_word_list = ["hoard", "exhibition", "utility", "snorkel", "side", "thompson", "arrival", "burmese", "modern", "ruin", "chin"]
rule3_word_list = ["state", "dol", "farmer", "herder", "cis", "nit", "hogan", "mead", "jay", "bolshevik", "israelite", "wren", "omen", "holly", "tamale"]
rule4_word_list = ["led", "coin", "rifling", "concert", "cave", "dribbling", "knuckle", "croquet", "lipstick", "causeway", "splinter", "buttress", "bolster", "churn", "shed", "swan", "seesaw", "jolly"]

In [4]:
def data_sample_to_example(sample_row, answer_label):
    import json
    
    example_template = """
<start_of_image><image_soft_token><end_of_image>
Word: {word}
---
Noun Senses:
{noun_sense_list}
---
Verb Senses:
{verb_sense_list}
---
Answer: {answer}"""
    word = sample_row["word"]
    sense_dict = json.loads(sample_row["senses"])
    if "noun_senses" in sense_dict:
        noun_sense_list = sense_dict["noun_senses"]
    else:
        noun_sense_list = []
    
    if "verb_senses" in sense_dict:
        verb_sense_list = sense_dict["verb_senses"]
    else:
        verb_sense_list = []
        
    noun_sense_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(noun_sense_list)])
    verb_sense_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(verb_sense_list)])
    
    example_prompt = example_template.format(
        word=word,
        noun_sense_list=noun_sense_str,
        verb_sense_list=verb_sense_str,
        answer=answer_label
    )
    
    return example_prompt

각 기준별로 프롬프트를 짜서 분류하도록 할 것인데, 순서는 다음과 같이 짤 생각이다.

1. 기준 2(이미지를 나타내는 sense가 없음)
1. 품사 분류(명사인가 동사인가)
1. 기준 4(해당하는 품사의 sense 셋이 하나 뿐인가)
1. 기준 3(일반 명사와 고유 명사가 섞인 경우인가)
1. 기준 1(sense간의 차이가 이미지로 구분 가능한가)

#### 기준 2: 이미지를 나타내는 sense가 있는가

In [5]:
prompt_zero_template = """
Distinguish whether the given word is valid for visual word sense disambiguation. 
Decide based on the following criteria:
* If there is a suitable sense in the sense set that can represent the given image, then the word is valid for visual word sense disambiguation. otherwise, it is invalid for visual word sense disambiguation.

---Word for evaluation: {word}---
Image: <start_of_image><image_soft_token><end_of_image>
---
Noun Senses:
{noun_sense_list}
---
Verb Senses:
{verb_sense_list}

Think step by step and provide a detailed explanation for your answer. Then, give the final answer in the format of 'Answer: Valid' or 'Answer: Invalid'.
"""

In [6]:
prompt_few_template = """
Distinguish whether the given word is valid for visual word sense disambiguation. 
Decide based on the following criteria:
* If there is a suitable sense in the sense set that can represent the given image, then the word is valid for visual word sense disambiguation. otherwise, it is invalid for visual word sense disambiguation.

Here are some examples of valid and invalid words for visual word sense disambiguation:
{example1}
---
{example2}
---

---Word for evaluation: {word}---
Image: <start_of_image><image_soft_token><end_of_image>
---
Noun Senses:
{noun_sense_list}
---
Verb Senses:
{verb_sense_list}

Think step by step and provide a detailed explanation for your answer. Then, give the final answer in the format of 'Answer: Valid' or 'Answer: Invalid'.
"""

In [18]:
# zero shot 셋 구축하기
base_df = pd.read_csv("/workspace/data/dataset_construction_train/train_set_base.csv")

import json
prompt_list = list()
for index, row in base_df.iterrows():
    sense_dict = json.loads(row["senses"])
    prompt = prompt_zero_template.format(
        word=row["word"],
        noun_sense_list="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(sense_dict.get("noun_senses", []))]),
        verb_sense_list="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(sense_dict.get("verb_senses", []))])
    )
    prompt_list.append(prompt)

rule2_indices = base_df[base_df["word"].isin(rule2_word_list)].index

base_df.loc[base_df.index, "label"] = "Valid"
base_df.loc[rule2_indices, "label"] = "Invalid"

base_df.loc[base_df.index, "prompt"] = prompt_list

base_df.to_csv("/workspace/data/dataset_construction_train/train_set_rule2_zero_shot_bench.csv", index=False)

In [7]:
valid_example_list = [] # 랜덤한 valid example 한 개 추출
invalid_example_list = ["utility"]

In [10]:
# few shot 셋 구축하기
base_df = pd.read_csv("/workspace/data/dataset_construction_train/train_set_base.csv")

invalid_df = base_df[base_df["word"].isin(rule2_word_list)]
valid_df = base_df[~base_df["word"].isin(rule2_word_list)]

valid_example_list = valid_df.sample(n=1, random_state=42)["word"].tolist()
valid_example_indices = valid_df[valid_df["word"].isin(valid_example_list)].index
invalid_example_indices = invalid_df[invalid_df["word"].isin(invalid_example_list)].index


# label 달기
base_df.loc[base_df.index, "label"] = "Valid"
base_df.loc[invalid_df.index, "label"] = "Invalid"

# example_df 저장
valid_example_df = base_df.loc[valid_example_indices]
invalid_example_df = base_df.loc[invalid_example_indices]

for index, row in valid_example_df.iterrows():
    valid_example_df.loc[index, "prompt"] = data_sample_to_example(row, "Valid")
for index, row in invalid_example_df.iterrows():
    invalid_example_df.loc[index, "prompt"] = data_sample_to_example(row, "Invalid")

example_df = pd.concat([valid_example_df, invalid_example_df], ignore_index=True)
example_df.to_csv("/workspace/data/dataset_construction_train/train_set_rule2_examples.csv", index=False)

base_df.drop(valid_example_indices, inplace=True)
base_df.drop(invalid_example_indices, inplace=True)

# 프롬프트 추가하기
import json
prompt_list = list()
for index, row in base_df.iterrows():
    sense_dict = json.loads(row["senses"])
    prompt = prompt_few_template.format(
        word=row["word"],
        noun_sense_list="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(sense_dict.get("noun_senses", []))]),
        verb_sense_list="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(sense_dict.get("verb_senses", []))]),
        example1=example_df.iloc[0]["prompt"],
        example2=example_df.iloc[1]["prompt"]
    )
    prompt_list.append(prompt)

base_df.loc[base_df.index, "prompt"] = prompt_list
base_df.to_csv("/workspace/data/dataset_construction_train/train_set_rule2_few_shot_bench.csv", index=False)

#### 기준 1: 이미지로 sense를 구분할 수 없음

In [59]:
prompt_template = """
Distinguish whether the given word is valid for visual word sense disambiguation. 
Decide based on the following criteria:
* If the given image for the word can not exclusively refer to one of the senses of the word, it is invalid for visual word sense disambiguation.

Here are some examples of valid and invalid words for visual word sense disambiguation:
{example1}
---
{example2}
---
{example3}
---
{example4}
---

---Word for evaluation: {word}---
Image: <start_of_image><image_soft_token><end_of_image>
---
Noun Senses:
{noun_sense_list}
---
Verb Senses:
{verb_sense_list}

Think step by step and provide a detailed explanation for your answer. Then, give the final answer in the format of 'Answer: Valid' or 'Answer: Invalid'.
"""

In [42]:
valid_example_list = [] # 랜덤한 valid example 두 개 추출
invalid_example_list = ["driftfish", "kindness"]

In [43]:
base_df = pd.read_csv("/workspace/data/dataset_construction_train/train_set_base.csv")

In [44]:
# 기준 1에 해당하는 단어의 index 추출
rule1_index_list = base_df[base_df["word"].isin(rule1_word_list)].index
invalid_df = base_df.loc[rule1_index_list]

invalid_df

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence
8,47,growling,"{""noun_senses"": [""a gruff or angry utterance (...",image.769.jpg,-1,NaN
21,96,rosinweed,"{""noun_senses"": [""North American perennial hav...",image.1509.jpg,-1,NaN
42,150,driftfish,"{""noun_senses"": [""larger butterfishes of the w...",image.2247.jpg,-1,NaN
57,230,mirror,"{""noun_senses"": [""polished surface that forms ...",image.3287.jpg,-1,NaN
63,246,happiness,"{""noun_senses"": [""state of well-being characte...",image.3487.jpg,-1,NaN
...,...,...,...,...,...,...
652,2494,autograph,"{""noun_senses"": [""something written by one's o...",image.2367.jpg,-1,NaN
685,2630,scholasticism,"{""noun_senses"": [""the system of philosophy dom...",image.5394.jpg,-1,NaN
691,2647,disagreement,"{""noun_senses"": [""a conflict of people's opini...",image.4661.jpg,-1,NaN
708,2713,music,"{""noun_senses"": [""an artistic form of auditory...",image.12003.jpg,-1,NaN
713,2741,lithography,"{""noun_senses"": [""a method of planographic pri...",image.10358.jpg,-1,NaN

In [45]:
valid_df = base_df.loc[~base_df.index.isin(rule1_index_list)]

In [46]:
# fewshot 예제로 활용할 valid example 2개 추출
valid_example_list = valid_df.sample(n=2, random_state=42)
valid_df = valid_df.drop(valid_example_list.index)

In [47]:
valid_example_df = valid_example_list

In [48]:
# fewshot 예제로 활용할 invalid example 2개 찾기
invalid_example_indices = base_df[base_df["word"].isin(invalid_example_list)].index
invalid_example_df = base_df.loc[invalid_example_indices]
invalid_df = invalid_df.drop(invalid_example_indices)
invalid_example_df

,word_index,word,senses,gold_image,gold_sense,ambiguous_sentence
42,150,driftfish,"{""noun_senses"": [""larger butterfishes of the w...",image.2247.jpg,-1,NaN
400,1553,kindness,"{""noun_senses"": [""the quality of being warmhea...",image.8675.jpg,-1,NaN

In [49]:
base_df = base_df.drop(valid_example_df.index)
base_df = base_df.drop(invalid_example_df.index)

In [50]:
base_df["label"] = "Valid"
base_df.loc[invalid_df.index, "label"] = "Invalid"

In [51]:
valid_example_df["label"] = "Valid"
invalid_example_df["label"] = "Invalid"
example_df = pd.concat([valid_example_df, invalid_example_df], ignore_index=False)

fewshot_prompts = list()
for index, row in example_df.iterrows():
    prompt = data_sample_to_example(row, row["label"])
    fewshot_prompts.append(prompt)

In [52]:
fewshot_prompts

['\n<start_of_image><image_soft_token><end_of_image>\nWord: listing\n---\nNoun Senses:\n1) a database containing an ordered array of items (names or topics)\n2) the act of making a list of items\n---\nVerb Senses:\n1) give or make a list of; name individually; give the names of\n2) include in a list\n3) cause to lean to the side\n4) tilt to one side\n5) enumerate\n---\nAnswer: Valid\n    ',
 "\n<start_of_image><image_soft_token><end_of_image>\nWord: draw\n---\nNoun Senses:\n1) a gully that is shallower than a ravine\n2) an entertainer who attracts large audiences\n3) the finish of a contest in which the score is tied and the winner is undecided\n4) anything (straws or pebbles etc.) taken or chosen at random\n5) a playing card or cards dealt or taken from the pack\n6) a golf shot that curves to the left for a right-handed golfer\n7) (American football) the quarterback moves back as if to pass and then hands the ball to the fullback who is running toward the line of scrimmage\n8) poker in which a player can discard cards and receive substitutes from the dealer\n9) the act of drawing or hauling something\n---\nVerb Senses:\n1) cause to move by pulling\n2) get or derive\n3) make a mark or lines on a surface\n4) make, formulate, or derive in the mind\n5) bring, take, or pull out of a container or from under a cover\n6) represent by making a drawing of, as with a pencil, chalk, etc. on a surface\n7) take liquid out of a container or well\n8) give a description of\n9) select or take in from a given group or region\n10) elicit responses, such as objections, criticism, applause, etc.\n11) suck in or take (air)\n12) move or go steadily or gradually\n13) remove (a commodity) from (a supply source)\n14) choose at random\n15) earn or achieve a base by being walked by the pitcher\n16) bring or lead someone to a certain action or condition\n17) cause to flow\n18) write a legal document or paper\n19) engage in drawing\n20) move or pull so as to cover or uncover something\n21) allow a draft\n22) require a specified depth for floating\n23) pull (a person) apart with four horses tied to his extremities, so as to execute him\n24) cause to move in a certain direction by exerting a force upon, either physically or in an abstract sense\n25) take in, also metaphorically\n26) direct toward itself or oneself by means of some psychological power or physical attributes\n27) thread on or as if on a string\n28) stretch back a bowstring (on an archer's bow)\n29) pass over, across, or through\n30) finish a game with an equal number of points, goals, etc.\n31) contract\n32) reduce the diameter of (a wire or metal rod) by pulling it through a die\n33) steep; pass through a strainer\n34) remove the entrails of\n35) flatten, stretch, or mold metal or glass, by rolling or by pulling it through a die or by stretching\n36) cause to localize at one point\n---\nAnswer: Valid\n    ",
 '\n<start_of_image><image_soft_token><end_of_image>\nWord: driftfish\n---\nNoun Senses:\n1) larger butterfishes of the western Atlantic from the New York area to the northern Gulf of Mexico\n2) small (6 inches) tropical butterfishes found worldwide\n---\nVerb Senses:\n\n---\nAnswer: Invalid\n    ',
 '\n<start_of_image><image_soft_token><end_of_image>\nWord: kindness\n---\nNoun Senses:\n1) the quality of being warmhearted and considerate and humane and sympathetic\n2) tendency to be kind and forgiving\n3) a kind act\n---\nVerb Senses:\n\n---\nAnswer: Invalid\n    ']

In [53]:
example_df["prompt"] = fewshot_prompts

In [54]:
example_df.to_csv("/workspace/data/dataset_construction_train/invalid1_examples.csv", index=False)

In [60]:
import json
prompt_list = list()
for index, row in base_df.iterrows():
    sense_dict = json.loads(row["senses"])
    prompt = prompt_template.format(
        word=row["word"],
        noun_sense_list="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(sense_dict.get("noun_senses", []))]),
        verb_sense_list="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(sense_dict.get("verb_senses", []))]),
        example1=example_df["prompt"].iloc[0],
        example2=example_df["prompt"].iloc[1],
        example3=example_df["prompt"].iloc[2],
        example4=example_df["prompt"].iloc[3]
    )
    prompt_list.append(prompt)

In [61]:
base_df["prompt"] = prompt_list

In [62]:
invalid1_bench_df = base_df.copy()

In [63]:
invalid1_bench_df.to_csv("/workspace/data/dataset_construction_train/invalid1_bench.csv", index=False)

#### 기준 2: 이미지를 나타내는 sense가 없음

In [ ]:
prompt_template = """
Word: {word}
---
Noun Senses:
{noun_sense_list}
---
Verb Senses:
{verb_sense_list}
---
Distinguish whether the given word is valid for visual word sense disambiguation. 
Decide based on the following criteria:
* If the given image for the word does not have , it is invalid for visual word sense disambiguation.

Here are some examples of valid and invalid words for visual word sense disambiguation:
{example1}
---
{example2}
---
{example3}
---
{example4}

Think step by step and provide a detailed explanation for your answer. Then, give the final answer in the format of 'Answer: Valid' or 'Answer: Invalid'.
"""

In [6]:
def annotate_samples(df):
    import json
    for index, row in df.iterrows():
        word = row["word"]
        senses = json.loads(row["senses"])
        noun_sense_list = senses["noun_senses"] if "noun_senses" in senses else []
        verb_sense_list = senses["verb_senses"] if "verb_senses" in senses else []
        
        noun_sense_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(noun_sense_list)])
        verb_sense_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(verb_sense_list)])
        
        prompt = prompt_template.format(word=word, noun_sense_list=noun_sense_str, verb_sense_list=verb_sense_str)
        
        label = ""
        if row["gold_sense"] != -1:
            label = senses["gold_pos"]
        else:
            label = "invalid"
        
        df.loc[index,"prompt"] = prompt
        df.loc[index,"label"] = label

## 다 필요없고 그냥 데이터셋 만들어라

### 정답 sense 찾기 task

In [1]:
import pandas as pd

entire_df = pd.read_csv("/workspace/data/set_process/wsd_set_n550.csv")

In [ ]:
# 원본 데이터셋으로부터 text sense 얻어오기
text_context_list = list()
with open("/workspace/data/semeval-2023-task-1-V-WSD-train-v1/train_v1/train.data.v1.txt", "rt") as f:
    for line in f:
        line_elements = line.strip().split("\t")
        text_context_list.append(line_elements[1])

In [5]:
context_list_column = list()
for index, row in entire_df.iterrows():
    word_index = row["word_index"]
    context_list_column.append(text_context_list[word_index])
entire_df["text_context"] = context_list_column

In [ ]:
# 프롬프트 때려박기
prompt_template = """Ambiguous Word: {word}
---
Noun senses:
{noun_senses}
---
Verb senses:
{verb_senses}
---
Perform Word Sense Disambiguation (WSD) for a specific word.
The image describes a specific sense of the word. Your task is to determine which sense of the word is being depicted in the image.

Determine the Part of Speech first. (Noun or Verb)
* If both Part of Speech are applicable, consider the sense list of each Part of Speech and choose the one that can be used more diversely in various contexts.

Then, answer with the number corresponding to the correct sense within the Part of Speech's sense list (1, 2, or 3).

The answer should be in the format of 'POS, Sense Number'. For example, 'Noun, 2' or 'Verb, 1'.
Do not provide any explanation, only give the final answer in the specified format."""

In [45]:
# PoS 태깅이 필요없을 때의 프롬프트 템플릿
prompt_template_no_pos = """Ambiguous Word: {word}
---
Sense List:
{senses}
---
Perform Word Sense Disambiguation (WSD) for a specific word.
The image describes a specific sense of the word. Your task is to determine which sense of the word is being depicted in the image.

Answer with the number corresponding to the correct sense within the Part of Speech's sense list (1, 2, or 3).

The answer should be in the format of 'Sense Number'. For example, '2' or '1'.
Do not provide any explanation, only give the final answer in the specified format."""

In [26]:
# PoS 태깅이 필요없을 때의 프롬프트 템플릿
prompt_template_no_pos_thinking = """Text Context: {text_context}
---
Ambiguous Word: {word}
---
Sense List:
{senses}
---
Perform Word Sense Disambiguation (WSD) for a specific word.
The image and text context describe a specific sense of the word. Your task is to determine which sense of the word is being described through the image and text context.
Don’t get bogged down in overly abstract reasoning; instead, think simply—just as the image depicts and the text describes—and choose the most direct interpretation.

Answer with the number corresponding to the correct sense within the Part of Speech's sense list (1, 2, or 3).

Before answering, think through the problem step by step. First describe the image with the given word and connect it to the text context. Then, try to explain the context using the senses one by one and determine which sense is most likely in given context. Finally, provide the answer in the specified format.
The answer should be in the format of 'A: Sense Number'. For example, 'A: 2' or 'A: 1'."""

In [27]:
import json
prompt_list = list()
for index, row in entire_df.iterrows():
    word = row["word"]
    
    sense_dict = json.loads(row["senses"])
    noun_senses = sense_dict["noun_senses"] if "noun_senses" in sense_dict else []
    verb_senses = sense_dict["verb_senses"] if "verb_senses" in sense_dict else []
    noun_senses_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(noun_senses)])
    verb_senses_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(verb_senses)])
    
    prompt = prompt_template.format(word=word, noun_senses=noun_senses_str, verb_senses=verb_senses_str)
    prompt_list.append(prompt)

entire_df["prompt"] = prompt_list

NameError: name 'prompt_template' is not defined

In [28]:
import json
prompt_list = list()
for index, row in entire_df.iterrows():
    word = row["word"]
    
    sense_dict = json.loads(row["senses"])
    senses = sense_dict["noun_senses"] if "noun_senses" in sense_dict else []
    if len(senses) == 0:
        senses = sense_dict["verb_senses"] if "verb_senses" in sense_dict else []
    senses_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(senses)])
    
    prompt = prompt_template_no_pos_thinking.format(word=word, senses=senses_str, text_context=row["text_context"])
    prompt_list.append(prompt)

entire_df["prompt"] = prompt_list

In [29]:
entire_df.to_csv("/workspace/data/set_process/wsd_labeled_wsd_think_prompt.csv", index=False)

#### PoS를 한정하지 않았을 때

쓸데없는 디테일이라고 레이블 단 것조차 쓸데없는 짓으로 매도당하기는 했지만, 그래도 평가 자체는 해야하고, 기존에 레이블 단 데이터셋이 있으니 평가를 해볼 수 있지 않을까.

In [19]:
import pandas as pd

pred_df = pd.read_csv("/workspace/data/set_process/inference/wsd_entire_results_gemma3-27b.csv")
labeled_df = pd.read_csv("/workspace/data/set_process/wsd_set_n550.csv")

In [20]:
import json
correct_count = 0
prediction_list = list()
label_list = list()
for index, row in labeled_df.iterrows():
    # label을 POS, sense number 형태로 바꿔주기
    sense_dict = json.loads(row["senses"])
    gold_pos = ""
    if "noun_senses" in sense_dict:
        gold_pos = "Noun"
    elif "verb_senses" in sense_dict:
        gold_pos = "Verb"
    
    label = f"{gold_pos}, {row['gold_sense']}"
    prediction = pred_df[pred_df["word_index"] == row["word_index"]]
    if len(prediction) > 0:
        prediction = prediction.iloc[0]["answer"]
    else:
        prediction = "No Prediction"
    
    prediction_list.append(prediction)
    label_list.append(label)

    if label == prediction:
        correct_count += 1

labeled_df["prediction"] = prediction_list
labeled_df["label"] = label_list

print(f"Correct predictions: {correct_count}/{len(labeled_df)}")

Correct predictions: 442/550

In [23]:
print("Accuracy:", correct_count / len(labeled_df))

Accuracy: 0.8036363636363636

In [25]:
labeled_df[labeled_df["prediction"] != labeled_df["label"]][["word", "senses", "gold_sense", "prediction", "label"]].iloc[:10]

,word,senses,gold_sense,prediction,label
1,upset,"{""verb_senses"": [""disturb the balance or stabi...",6,"Verb, 2","Verb, 6"
3,beater,"{""noun_senses"": [""a worker who rouses wild gam...",3,"Noun, 2","Noun, 3"
5,paddle,"{""verb_senses"": [""propel with a paddle"", ""play...",5,"Noun, 3","Verb, 5"
11,enlightenment,"{""noun_senses"": [""education that results in un...",1,"Noun, 2","Noun, 1"
12,pica,"{""noun_senses"": [""an eating disorder, frequent...",1,"Noun, 3","Noun, 1"
14,bottle,"{""verb_senses"": [""store (liquids or gases) in ...",2,"Noun, 1","Verb, 2"
16,discrimination,"{""noun_senses"": [""unfair treatment of a person...",1,"Noun, 2","Noun, 1"
25,drama,"{""noun_senses"": [""a dramatic work intended for...",1,"Noun, 2","Noun, 1"
28,throw,"{""noun_senses"": [""the act of throwing (propell...",1,"Verb, 1","Noun, 1"
31,wolverine,"{""noun_senses"": [""a native or resident of Mich...",2,"Noun, 3","Noun, 2"

PoS를 한정하지 않고 모든 sense를 주고 예측하도록 하였을 때 정확도는 80.36%

#### PoS를 한정하였을 때

In [74]:
pred_df = pd.read_csv("/workspace/data/set_process/inference/wsd_labeled_results_gemma3-27b.csv")

In [75]:
correct_count = 0
for index, row in pred_df.iterrows():
    label = row["gold_sense"]
    prediction = int(row["answer"])

    if label == prediction:
        correct_count += 1

print(f"Correct predictions: {correct_count}/{len(pred_df)}")
print("Accuracy:", correct_count / len(pred_df))

Correct predictions: 471/550
Accuracy: 0.8563636363636363

정확도가 85.63%로 상승

In [80]:
pred_df[pred_df["answer"] != pred_df["gold_sense"]][["word", "senses", "gold_sense", "answer"]].iloc[:10]

,word,senses,gold_sense,answer
0,moorhen,"{""noun_senses"": [""black gallinule that inhabit...",1,The image shows birds with dark plumage and di...
1,upset,"{""verb_senses"": [""disturb the balance or stabi...",6,The image depicts the biblical scene of David ...
2,breakdown,"{""noun_senses"": [""the act of disrupting an est...",3,Here's a breakdown of the problem and the solu...
3,beater,"{""noun_senses"": [""a worker who rouses wild gam...",3,"The image shows a woman at a loom, weaving. Th..."
4,sprat,"{""noun_senses"": [""small fatty European fish; u...",1,"The image shows a small, silvery fish. This fi..."
5,paddle,"{""verb_senses"": [""propel with a paddle"", ""play...",5,Here's a breakdown of the image and the word s...
6,beech,"{""noun_senses"": [""any of several large deciduo...",1,The image depicts a botanical illustration of ...
7,patient,"{""noun_senses"": [""a person who requires medica...",1,The image shows three people sitting in chairs...
8,student,"{""noun_senses"": [""a learner who is enrolled in...",1,"The image shows a large group of people, mostl..."
9,runner,"{""noun_senses"": [""someone who imports or expor...",6,"The image shows a man running on a beach path,..."

#### PoS 한정 및 thinking 추가

In [17]:
pred_df = pd.read_csv("/workspace/data/set_process/inference/wsd_labeled_think_results_gemma3-27b.csv")

In [18]:
correct_count = 0
prediction_list = list()
for index, row in pred_df.iterrows():
    label = row["gold_sense"]
    prediction = int(row["answer"].split("A:")[-1].strip())
    prediction_list.append(prediction)
    
    if label == prediction:
        correct_count += 1

pred_df["prediction"] = prediction_list
print(f"Correct predictions: {correct_count}/{len(pred_df)}")
print("Accuracy:", correct_count / len(pred_df))

Correct predictions: 481/550
Accuracy: 0.8745454545454545

In [24]:
# 10개씩 보기
starting_point = 0

pred_df[pred_df["prediction"] != pred_df["gold_sense"]][["word", "senses", "gold_sense", "prediction"]].iloc[starting_point:starting_point+10]

,word,senses,gold_sense,prediction
1,upset,"{""verb_senses"": [""disturb the balance or stabi...",6,3
9,runner,"{""noun_senses"": [""someone who imports or expor...",6,2
12,pica,"{""noun_senses"": [""an eating disorder, frequent...",1,3
16,discrimination,"{""noun_senses"": [""unfair treatment of a person...",1,2
43,drought,"{""noun_senses"": [""a shortage of rainfall"", ""a ...",1,2
47,core,"{""noun_senses"": [""a small group of indispensab...",8,2
58,paint,"{""verb_senses"": [""make a painting"", ""apply pai...",1,2
72,reflexion,"{""noun_senses"": [""the phenomenon of a propagat...",7,6
96,whip,"{""verb_senses"": [""beat severely with a whip or...",4,3
99,ennoblement,"{""noun_senses"": [""the state of being noble"", ""...",1,2

#### PoS 한정 및 thinking 추가, text context 추가

In [21]:
pred_tc_df = pd.read_csv("/workspace/data/set_process/inference/wsd_labeled_think_textContext_gemma3-27b.csv")

In [22]:
correct_count = 0
prediction_list = list()
for index, row in pred_tc_df.iterrows():
    label = row["gold_sense"]
    prediction = int(row["answer"].split("A:")[-1].strip())
    prediction_list.append(prediction)
    
    if label == prediction:
        correct_count += 1

pred_tc_df["prediction"] = prediction_list
print(f"Correct predictions: {correct_count}/{len(pred_tc_df)}")
print("Accuracy:", correct_count / len(pred_tc_df))

Correct predictions: 494/550
Accuracy: 0.8981818181818182

In [25]:
# 10개씩 보기
starting_point = 0

pred_tc_df[pred_tc_df["prediction"] != pred_tc_df["gold_sense"]][["word", "senses", "gold_sense", "prediction"]].iloc[starting_point:starting_point+10]

,word,senses,gold_sense,prediction
1,upset,"{""verb_senses"": [""disturb the balance or stabi...",6,1
9,runner,"{""noun_senses"": [""someone who imports or expor...",6,2
16,discrimination,"{""noun_senses"": [""unfair treatment of a person...",1,2
35,siren,"{""noun_senses"": [""a sea nymph (part woman and ...",1,2
40,funfair,"{""noun_senses"": [""a commercially operated park...",1,2
58,paint,"{""verb_senses"": [""make a painting"", ""apply pai...",1,2
99,ennoblement,"{""noun_senses"": [""the state of being noble"", ""...",1,2
130,butchery,"{""noun_senses"": [""a building where animals are...",2,1
133,bar,"{""noun_senses"": [""a room or establishment wher...",1,2
139,upholstery,"{""noun_senses"": [""covering (padding and spring...",2,1

#### PoS 한정 및 thinking 추가, text context 추가 v2

In [30]:
pred_tc_df = pd.read_csv("/workspace/data/set_process/inference/wsd_labeled_think_textContext_v2_gemma3-27b.csv")

correct_count = 0
prediction_list = list()
for index, row in pred_tc_df.iterrows():
    label = row["gold_sense"]
    prediction = int(row["answer"].split("A:")[-1].strip())
    prediction_list.append(prediction)
    
    if label == prediction:
        correct_count += 1

pred_tc_df["prediction"] = prediction_list
print(f"Correct predictions: {correct_count}/{len(pred_tc_df)}")
print("Accuracy:", correct_count / len(pred_tc_df))

Correct predictions: 490/550
Accuracy: 0.8909090909090909

### 모호한 문장 생성 프롬프트

In [ ]:
import pandas as pd

wsd_df = pd.read_csv("/workspace/data/set_process/inference/wsd_entire_wsd_prompt_results_gemma3-27b.csv")

In [ ]:
invalid_indices = list()
for index, row in wsd_df.iterrows():
    answer = row["answer"].strip().lower()
    
    answer_list = answer.split(',')
    if (len(answer_list) != 2) or \
        (answer_list[0].strip() not in ["noun", "verb"]) or \
        (not answer_list[1].strip().isdigit()):
        invalid_indices.append(index)

# invalid한 답변이 몇 개나 있는지 확인
print(f"Invalid answer indices: {invalid_indices}")

In [ ]:
filtered_wsd_df = wsd_df.drop(index=invalid_indices)

In [ ]:
pos_list = list()
sense_number_list = list()
for index, row in filtered_wsd_df.iterrows():
    answer = row["answer"].strip().lower()
    
    answer_list = answer.split(',')
    pos = answer_list[0].strip()
    sense_number = int(answer_list[1].strip())

    pos_list.append(pos)
    sense_number_list.append(sense_number)
    
filtered_wsd_df["predicted_pos"] = pos_list
filtered_wsd_df["predicted_sense_number"] = sense_number_list

In [ ]:
# 예측한 pos의 sense list에 하나의 sense만 들어있는 경우 확인
import json

invalid_indices = list()
for index, row in filtered_wsd_df.iterrows():
    predicted_pos = row["predicted_pos"]
    sense_dict = json.loads(row["senses"])
    if predicted_pos == "noun":
        sense_list = sense_dict["noun_senses"] if "noun_senses" in sense_dict else []
    elif predicted_pos == "verb":
        sense_list = sense_dict["verb_senses"] if "verb_senses" in sense_dict else []
    else:
        sense_list = []
    
    if len(sense_list) <= 1:
        invalid_indices.append(index)

print(f"Indices with only one or zero senses for the predicted POS: {invalid_indices}")

In [ ]:
# 한번더 필터링
filtered_wsd_df = wsd_df.drop(index=invalid_indices)
print("Valid sample count after filtering:", len(filtered_wsd_df))

# 원본 데이터셋 분석

## 원본 데이터셋의 품사 분석

원본 데이터셋 phrase 품사 통계 분석하기

"왜 noun과 verb 중 하나를 선택하는가"에 대한 근가가 필요한 상황

In [1]:
with open("/workspace/data/semeval-2023-task-1-V-WSD-train-v1/train_v1/train.data.v1.txt", "rt") as fp:
    data = fp.readlines()

    print(data[0].split("\t"))

['moorhen', 'moorhen swamphen', 'image.3.jpg', 'image.8.jpg', 'image.4.jpg', 'image.1.jpg', 'image.2.jpg', 'image.0.jpg', 'image.5.jpg', 'image.6.jpg', 'image.7.jpg', 'image.9.jpg\n']

In [2]:
phrase_list = list()
word_list = list()
with open("/workspace/data/semeval-2023-task-1-V-WSD-train-v1/train_v1/train.data.v1.txt", "rt") as fp:
    data = fp.readlines()
    
    for line in data:
        split_line = line.split("\t")
        word_list.append(split_line[0])
        phrase_list.append(split_line[1])

In [3]:
import nltk
from nltk.tokenize import word_tokenize

tokens = word_tokenize(phrase_list[0])
tags = nltk.pos_tag(tokens)
print(tags)

[('moorhen', 'NN'), ('swamphen', 'NN')]

In [4]:
# Pos tag list
pos_list = list()
for idx in range(len(word_list)):
    tokens = word_tokenize(phrase_list[idx])
    tags = nltk.pos_tag(tokens)

    word_tokens = word_tokenize(word_list[idx])
    #assert len(word_tokens) == 1, f"The word {word_list[idx]} should be a single token."
    
    if len(word_tokens) > 1:
        print(f"Warning: The word '{word_list[idx]}' is tokenized into multiple tokens: {word_tokens}. Using the first token for POS tagging.")
        pos_list.append("N/A")
    else:
        # 관심 있는 단어의 pos tag 찾기
        find_idx = tokens.index(word_list[idx])
        pos_list.append(tags[find_idx][1])

Warning: The word '“nits”' is tokenized into multiple tokens: ['“', 'nits', '”']. Using the first token for POS tagging.
Warning: The word 'g&s' is tokenized into multiple tokens: ['g', '&', 's']. Using the first token for POS tagging.
Warning: The word 'o.v.n.i.' is tokenized into multiple tokens: ['o.v.n.i', '.']. Using the first token for POS tagging.
Warning: The word 'areca-nut palm' is tokenized into multiple tokens: ['areca-nut', 'palm']. Using the first token for POS tagging.
Warning: The word '(e,e)-sa' is tokenized into multiple tokens: ['(', 'e', ',', 'e', ')', '-sa']. Using the first token for POS tagging.
Warning: The word '`id-ul-mawta' is tokenized into multiple tokens: ['`', 'id-ul-mawta']. Using the first token for POS tagging.
Warning: The word 'mac&cheese' is tokenized into multiple tokens: ['mac', '&', 'cheese']. Using the first token for POS tagging.
Warning: The word 's.o.p.' is tokenized into multiple tokens: ['s.o.p', '.']. Using the first token for POS tagging.
Warning: The word 's&e' is tokenized into multiple tokens: ['s', '&', 'e']. Using the first token for POS tagging.
Warning: The word 'a.m.p.a.s.' is tokenized into multiple tokens: ['a.m.p.a.s', '.']. Using the first token for POS tagging.
Warning: The word 'durkee–mower' is tokenized into multiple tokens: ['durkee', '–', 'mower']. Using the first token for POS tagging.
Warning: The word 'v.p.o.t.u.s.' is tokenized into multiple tokens: ['v.p.o.t.u.s', '.']. Using the first token for POS tagging.
Warning: The word 'marfan's' is tokenized into multiple tokens: ['marfan', "'s"]. Using the first token for POS tagging.
Warning: The word 'z$' is tokenized into multiple tokens: ['z', '$']. Using the first token for POS tagging.
Warning: The word 'tt$' is tokenized into multiple tokens: ['tt', '$']. Using the first token for POS tagging.
Warning: The word 'maksutov–cassegrain' is tokenized into multiple tokens: ['maksutov', '–', 'cassegrain']. Using the first token for POS tagging.
Warning: The word 'turner's' is tokenized into multiple tokens: ['turner', "'s"]. Using the first token for POS tagging.
Warning: The word ''midnight'' is tokenized into multiple tokens: ["'midnight", "'"]. Using the first token for POS tagging.

In [5]:
# dataframe으로 구성하기
import pandas as pd
data_dict = {
    "word": word_list,
    "phrase": phrase_list,
    "pos_tag": pos_list
}
df = pd.DataFrame(data_dict)

df

              word              phrase pos_tag
0          moorhen    moorhen swamphen      NN
1          serinus       serinus genus      NN
2        pegmatite   pegmatite igneous      RB
3       bangalores  bangalores torpedo     NNS
4           bonxie         bonxie skua      NN
...            ...                 ...     ...
12864      bomarea       bomarea genus      NN
12865   tragopogon    tragopogon genus      NN
12866  illustrator  illustrator artist      NN
12867   brunfelsia    brunfelsia genus      NN
12868     headband       headband band      NN

[12869 rows x 3 columns]

In [6]:
df["pos_tag"].value_counts()

pos_tag
NN     8836
NNS    1708
JJ     1623
VBG     285
RB      207
VB       41
CD       35
JJR      30
DT       27
VBN      20
N/A      18
IN       17
JJS       7
RBR       4
NNP       2
FW        2
WP        2
PRP       1
MD        1
$         1
VBD       1
RBS       1
Name: count, dtype: int64

In [7]:
df[df["pos_tag"] == "JJ"]

               word                  phrase pos_tag
11            upset           upset success      JJ
14        breakdown       breakdown failure      JJ
16     leucanthemum      leucanthemum genus      JJ
33           paddle             paddle beat      JJ
66        rewa-rewa          rewa-rewa tree      JJ
...             ...                     ...     ...
12823         scuba       scuba free-diving      JJ
12829         logic        logic philosophy      JJ
12839  veterinarian  veterinarian physician      JJ
12844    tug-of-war    tug-of-war athletics      JJ
12862       tarnish   tarnish discoloration      JJ

[1623 rows x 3 columns]

In [8]:
import json
# 레이블 단 데이터셋 가져와서 겹쳐놓고 보자
labeled_df = pd.read_csv("/workspace/data/dataset_construction_train/train_set_base.csv")

# 마지막 단어를 기준으로 순회
last_word = labeled_df["word"].iloc[-1]

# 원본 데이터셋에서의 last_word의 index 찾기
last_word_index = df[df["word"] == last_word].index[0]

# 0번 인덱스부터 순회
df_index = 0
index_list = list()
image_list = list()
label_list = list()
while df_index <= last_word_index:
    cur_word = df["word"].iloc[df_index]
    index_list.append(df_index)
    if cur_word in labeled_df["word"].values:
        cur_row = labeled_df[labeled_df["word"] == cur_word]
        image_list.append(cur_row["gold_image"].iloc[0])
        sense_dict = json.loads(cur_row["senses"].iloc[0])
        gold_pos = sense_dict.get("gold_pos", "N/A")
        label_list.append(gold_pos)
    else:
        image_list.append("N/A")
        label_list.append("Filtered")
    
    df_index += 1

In [99]:
import json
sense_dict = json.loads(labeled_df[labeled_df["word_index"] == 2669]["senses"].iloc[0])
sense_list = sense_dict.get("noun_senses")
sense_str = "\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(sense_list)])
print(sense_str)

1) the protruding part of the lower jaw
2) Kamarupan languages spoken in western Burma and Bangladesh and easternmost India

In [9]:
dataset_df = df.loc[index_list]

dataset_df["gold_image"] = image_list
dataset_df["label"] = label_list

dataset_df["label"].value_counts()

label
Filtered    2032
noun         518
N/A          121
verb          86
Name: count, dtype: int64

In [10]:
dataset_df

             word                   phrase pos_tag      gold_image     label
0         moorhen         moorhen swamphen      NN     image.0.jpg      noun
1         serinus            serinus genus      NN             N/A  Filtered
2       pegmatite        pegmatite igneous      RB             N/A  Filtered
3      bangalores       bangalores torpedo     NNS             N/A  Filtered
4          bonxie              bonxie skua      NN             N/A  Filtered
...           ...                      ...     ...             ...       ...
2752       velour            velour fabric     NNS             N/A  Filtered
2753     mayapple            mayapple herb      NN             N/A  Filtered
2754  chelicerata        chelicerata class     NNS             N/A  Filtered
2755   eptatretus       eptatretus hagfish      NN             N/A  Filtered
2756    shakedown  shakedown accommodation      JJ  image.2859.jpg      noun

[2757 rows x 5 columns]

사실상 2700개 중에 2000개, 즉 거의 대부분이 필터링된 상태인데 필터링된 애들의 품사를 살펴보자

In [83]:
dataset_df["pos_tag"].value_counts()

pos_tag
NN     1909
NNS     363
JJ      319
VBG      75
RB       40
VB       11
DT       10
VBN       9
CD        9
JJR       5
RBR       2
N/A       1
IN        1
NNP       1
PRP       1
MD        1
Name: count, dtype: int64

In [84]:
dataset_df[dataset_df["label"] == "Filtered"]["pos_tag"].value_counts()

pos_tag
NN     1345
NNS     324
JJ      249
VBG      55
RB       25
CD        9
VB        7
DT        6
VBN       5
JJR       2
RBR       1
N/A       1
IN        1
NNP       1
PRP       1
Name: count, dtype: int64

In [11]:
dataset_df[dataset_df["label"] != "Filtered"]["pos_tag"].value_counts()

pos_tag
NN     564
JJ      70
NNS     39
VBG     20
RB      15
VBN      4
DT       4
VB       4
JJR      3
RBR      1
MD       1
Name: count, dtype: int64

In [12]:
dataset_df[dataset_df["label"] == "N/A"]["pos_tag"].value_counts()

pos_tag
NN     84
JJ     16
VBG     7
NNS     7
VBN     3
RB      2
DT      1
JJR     1
Name: count, dtype: int64

In [44]:
JJ_rate = dataset_df[dataset_df["label"] == "Filtered"]["pos_tag"].value_counts()["JJ"]/dataset_df["label"].value_counts()["Filtered"]
print(f"JJ rate in filtered samples: {JJ_rate:.2f}")

JJ rate in filtered samples: 0.12

In [45]:
parameter_value = len(dataset_df) - dataset_df["label"].value_counts()["Filtered"]
JJ_rate = dataset_df[dataset_df["label"] != "Filtered"]["pos_tag"].value_counts()["JJ"]/parameter_value
print(f"JJ rate in non-filtered samples: {JJ_rate:.2f}")

JJ rate in non-filtered samples: 0.10

In [13]:
parameter_value = dataset_df["label"].value_counts()["N/A"]
JJ_rate = dataset_df[dataset_df["label"] == "N/A"]["pos_tag"].value_counts()["JJ"]/parameter_value
print(f"JJ rate in N/A samples: {JJ_rate:.2f}")

JJ rate in N/A samples: 0.13

형용사가 상당한 비율로 들어있지만, 결과적으로 필터링된 데이터, 레이블이 들어간 데이터, 레이블 과정에서 제외된 데이터 모두 형송사 비율이 일정하다.

즉, 이미 레이블을 단 데이터에 원본 문구에서 형용사로 뽑힌 케이스가 큰 역할을 하지는 않았다고 볼 수 있다.

In [14]:
# Verb인 애들 중 품사 비율
dataset_df[dataset_df["label"] == "verb"]["pos_tag"].value_counts()

pos_tag
NN     63
JJ     11
NNS     3
RB      3
VB      3
VBN     1
VBG     1
JJR     1
Name: count, dtype: int64

In [15]:
dataset_df[dataset_df["label"] == "noun"]["pos_tag"].value_counts()

pos_tag
NN     417
JJ      43
NNS     29
VBG     12
RB      10
DT       3
JJR      1
VB       1
RBR      1
MD       1
Name: count, dtype: int64

## 실제로 JJ까지 포함해서 뽑아보기

wordnet으로 형용사가 복수로 들어간 애들을 뽑아보고, 기존에 filter 안 된 애들이 얼마나 있는지 살펴보자

In [16]:
# dataset_df가 구축된 상태라고 가정
from nltk.corpus import wordnet as wn

adj_filter_list = list()
for row in dataset_df.itertuples():
    word = row.word
    phrase = row.phrase
    pos_tag = row.pos_tag
    label = row.label
    
    sense_list = wn.synsets(word)
    adj_sense_list = [sense for sense in sense_list if (sense.pos() == "a") or (sense.pos() == "s")]
    if len(adj_sense_list) > 1:
        adj_filter_list.append("Applicable")
    else:
        adj_filter_list.append("Inapplicable")

dataset_df["adj_filter"] = adj_filter_list

In [90]:
dataset_df["adj_filter"].value_counts()

adj_filter
Inapplicable    2719
Applicable        38
Name: count, dtype: int64

In [17]:
dataset_df[(dataset_df["adj_filter"] == "Applicable") & (dataset_df["label"] == "Filtered")]

,word,phrase,pos_tag,gold_image,label,adj_filter
160,friendly,friendly game,JJ,N/A,Filtered,Applicable
240,august,august month,JJ,N/A,Filtered,Applicable
713,mineral,mineral material,JJ,N/A,Filtered,Applicable
1257,grotesque,grotesque art,JJ,N/A,Filtered,Applicable
1431,madder,madder madderwort,NN,N/A,Filtered,Applicable
1474,physical,physical examination,JJ,N/A,Filtered,Applicable
1582,chemical,chemical material,JJ,N/A,Filtered,Applicable
1707,bridal,bridal marriage,JJ,N/A,Filtered,Applicable
2193,downy,downy mildew,NN,N/A,Filtered,Applicable
2220,jerky,jerky meat,NN,N/A,Filtered,Applicable
2292,screaming,screaming noise,VBG,N/A,Filtered,Applicable
2505,epic,epic poetry,NN,N/A,Filtered,Applicable
2636,military,military force,JJ,N/A,Filtered,Applicable
2681,instrumental,instrumental music,JJ,N/A,Filtered,Applicable

In [18]:
dataset_df[(dataset_df["adj_filter"] == "Applicable") & (dataset_df["label"] == "N/A")]

       word      phrase pos_tag       gold_image label  adj_filter
1754  solid  solid ball      JJ  image.10890.jpg   N/A  Applicable

주어진 문구에서 관심있는 단어가 형용사로 쓰인 경우는 많지만, 정작 형용사 sense로 다의어가 되는 경우는 드물다. 

* 전체 데이터셋 2750여 개 가운데 고작 38개
* sense로 필터링한 데이터셋 718개 중에 누락된 것 14개, 레이블링 과정에서 누락된 것 3개. 종합하면 17개로 약 2.4%에 불과하다.

In [61]:
# dataset_df가 구축된 상태라고 가정
# noun에 대해서도 어떤지 살펴보기
noun_filter_list = list()
for row in dataset_df.itertuples():
    word = row.word
    phrase = row.phrase
    pos_tag = row.pos_tag
    label = row.label
    
    sense_list = wn.synsets(word)
    noun_sense_list = [sense for sense in sense_list if sense.pos() == "n"]
    if len(noun_sense_list) > 1:
        noun_filter_list.append("Applicable")
    else:
        noun_filter_list.append("Inapplicable")

dataset_df["noun_filter"] = noun_filter_list

In [62]:
dataset_df["noun_filter"].value_counts()

noun_filter
Inapplicable    2094
Applicable       663
Name: count, dtype: int64

In [63]:
# dataset_df가 구축된 상태라고 가정
# verb에 대해서도 어떤지 살펴보기

verb_filter_list = list()
for row in dataset_df.itertuples():
    word = row.word
    phrase = row.phrase
    pos_tag = row.pos_tag
    label = row.label
    
    sense_list = wn.synsets(word)
    verb_sense_list = [sense for sense in sense_list if sense.pos() == "v"]
    if len(verb_sense_list) > 1:
        verb_filter_list.append("Applicable")
    else:
        verb_filter_list.append("Inapplicable")

dataset_df["verb_filter"] = verb_filter_list

In [64]:
dataset_df["verb_filter"].value_counts()

verb_filter
Inapplicable    2492
Applicable       265
Name: count, dtype: int64

중복된 것을 감안하더라도 명사 다의어는 663개나 되고, 동사 다의어도 265개가 된다. 이는 형용사의 38개에 비하면 훨씬 많다.

## 결론

다의어를 고려할 때 품사로 명사와 동사를 선택한 것은 통계적으로도 증명할 수 있는 좋은 선택이었다.

이외에도 이 통계는 원본 VWSD 데이터셋 자체가 언어적 특성을 무시한 채 이미지 concept 구분 task로 한정되었다는 좋은 증거가 된다.

# Test Dataset에서의 task 수행

## pos 분별하기

In [19]:
prompt_template="""
Ambiguous word: {word}
---
{sense_list}

You are an expert linguistic annotator. Image, a specific target word found within the context of that image, and a list of potential senses for that word are given. Each sense is categorized by a Part of Speech (POS): {pos_list}.

Your goal is to determine the correct POS by selecting the sense that most directly aligns with the visual context.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

{rule_list}

Always consider which sense can be most directly and concretely represented in the image. Avoid overcomplicating the reasoning process; focus on the most straightforward interpretation of the visual information in relation to the senses provided.

---
After all your reasoning is finished, provide your final decision as the format 'A: [POS]', where [POS] is your chosen Part of Speech ({pos_list}).
"""

noun_template = """Noun Senses:
{noun_senses}
"""
verb_template = """Verb Senses:
{verb_senses}
"""
adj_template = """Adjective Senses:
{adj_senses}
"""
adv_template = """Adverb Senses:
{adv_senses}
"""

noun_rules = "Every photo features an object. Therefore, consider nouns first."
verb_rules = """Verb is considered when:
* no noun sense is provided.
* the photo depicts an action—either directly or indirectly—rather than the object itself, and if there is a verb sense in the provided list that corresponds to the action shown in the photo."""
adj_rules = """Adjective is considered when:
* the photo can not be considered to depict an object or action of given word.
* the photo depicts a state rather than an action or an object itself, and there is a corresponding sense in the list of adjectives"""
adv_rules = """Adverb is considered when:
* the photo can not be considered to depict an object or action or state of given word."""

In [20]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    noun_senses = sense_dict.get("n", [])
    verb_senses = sense_dict.get("v", [])
    adj_senses = sense_dict.get("a", [])
    adv_senses = sense_dict.get("r", [])
    
    pos_list = list()
    sense_string = ""
    rule_string = ""
    if len(noun_senses) > 0:
        sense_string += (noun_template.format(noun_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(noun_senses)])) + "\n---\n")
        #rule_string += noun_rules + '\n\n'
        pos_list.append("noun")
    if len(verb_senses) > 0:
        sense_string += (verb_template.format(verb_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(verb_senses)])) + "\n---\n")
        rule_string += verb_rules + '\n\n'
        pos_list.append("verb")
    if len(adj_senses) > 0:
        sense_string += (adj_template.format(adj_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(adj_senses)])) + "\n---\n")
        rule_string += adj_rules + '\n\n'
        pos_list.append("adjective")
    if len(adv_senses) > 0:
        sense_string += (adv_template.format(adv_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(adv_senses)])) + "\n---\n")
        rule_string += adv_rules + '\n\n'
        pos_list.append("adverb")
    
    prompt = prompt_template.format(
        word=row["word"],
        sense_list=sense_string,
        pos_list=", ".join(pos_list),
        rule_list=rule_string,
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_100_pos3_prompt.csv", index=False)

## 정답 sense 찾기

### text만으로 zero shot 수행

In [11]:
prompt_template="""Text Context: {context}
Ambiguous Word: {word}
---
Sense List:
{sense_list}
---
You are an expert linguistic annotator. A specific target word found within the context of a given text, and a list of potential senses for that word are provided. Your task is to determine the correct sense by selecting the one that most directly aligns with the context and its background event.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

Prioritize the sense that best fits the given context, even if it is not the most direct match for the visual content.
---
After all your reasoning is finished, provide your final decision as the format 'A: [sense number]' and end your generation. In here, [sense number] is the index of your chosen sense from the provided list.
"""

In [12]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    prompt = prompt_template.format(
        word=row["word"],
        context=row["word_phrase"],
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_100_sense_text_prompt.csv", index=False)

### 이미지 context로 inference 수행

In [13]:
prompt_template="""Text Context: {context}
Ambiguous Word: {word}
---
Sense List:
{sense_list}
---
You are an expert linguistic annotator. A specific target word related to the given context, and a list of potential senses for that word are provided. Your task is to determine the correct sense by selecting the one that most directly aligns with the context and its background event.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

First, take a look at the 'Text Context' and the image. Leverage both context to analyze any significant background context is provided in the image. If such information exists, prioritize the sense that best fits this background information, even if it is not the most direct match for the visual content.

Directness of Meaning: If no additional background information can be obtained from the web search results, choose the sense that provides the most direct and specific fit for the visual and linguistic context. Even if a perfect match does not exist, select the sense that is the closest indirect match.
---
After all your reasoning is finished, provide your final decision as the format 'A: [sense number]' and end your generation. In here, [sense number] is the index of your chosen sense from the provided list.
"""

In [14]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    prompt = prompt_template.format(
        word=row["word"],
        context=row["word_phrase"],
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_100_sense_prompt.csv", index=False)

### 이미지 검색 정보로 inference 수행

#### sub task 1: 각 페이지 내용 요약

In [1]:
import trafilatura
import requests

def extract_clean_text(url):
    try:
        response = requests.get(url)
    except:
        return None

    if response.status_code == 200:
        downloaded = trafilatura.fetch_url(url)
        # 본문만 추출 (광고, 네비게이션 자동 제거)
        result = trafilatura.extract(downloaded, include_comments=False, include_tables=True)
        return result
    return None

In [2]:
prompt_template="""Ambiguous word: {word}
Context Phrase: {context}
Entites in Image: 
{entities}
---
You are a linguistic expert. Given 'Ambiguous Word', 'Context Phrase', and 'Entities in Image', your task is to extract and summarize any additional and helpful information from the given 'Searched Web Content' that can help explain the context of the image in relation to the 'Ambiguous Word'. Do not try to describe the image itself if there is no relevant information in the 'Searched Web Content' that can be helpful for understanding the 'Ambiguous Word'.
---
Searched Web Content:
- Title: {web_title}
- {text_context}
---
First, Refer to the 'Entities in Image' section to understand the content of the image. Then, read the 'Searched Web Content' section carefully and judge whether it is related to the '{context}', '{word}'. If there is some releavant information for '{word}', generate a word 'Relevant', otherwise generate a word 'Not Relevant'. If the first line is 'Relevant', generate a summary of the helpful information in the 'Searched Web Content' that can explain the context of the image in relation to the 'Ambiguous Word'. If the first line is 'Not Relevant', do not generate any summary and end your generation.
"""

In [3]:
import json
import pandas as pd
from tqdm.auto import tqdm
# 기존에 retrive하여 저장해놓은 목록에서 test 셋에 해당하는 100개 내역 얻어오기
wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")

# k =3
# 요약은 한 번의 LLM 호출로 하나의 인터넷 문서만 처리하도록 구조 적용
retrieval_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_entire_google_vision_result.csv")

df_dict = {
    "word_index": [],
    "word": [],
    "word_phrase": [],
    "senses": [],
    "gold_image": [],
    "gold_pos": [],
    "gold_sense": [],
    "prompt": []
}
for index, row in tqdm(wsd_test_df.iterrows(), total=len(wsd_test_df)):
    word_index = row["word_index"]
    retrieved_rows = retrieval_df[retrieval_df["word_index"] == word_index]
    retrieved_urls = json.loads(retrieved_rows["web_urls"].iloc[0])
    retrieved_entities = json.loads(retrieved_rows["entities"].iloc[0])
    if len(retrieved_entities) > 0:
        valid_entites = [retrieved_entities[0]["description"]]
        for entity in retrieved_entities[1:]:
            if entity["score"] >= 1.0:
                valid_entites.append(entity["description"])
        valid_entites = "\n".join([f"- {entity}" for entity in valid_entites])
    else:
        valid_entites = ""
    
    retrieved_urls_num = 0
    url_idx = 0
    none_page_titles = list()
    while url_idx < len(retrieved_urls) and retrieved_urls_num < 3:
        cur_url = retrieved_urls[url_idx]["url"]
        cur_title = retrieved_urls[url_idx]["title"]
        if "www.youtube.com" in cur_url:
            web_content = None
        else:
            web_content = extract_clean_text(cur_url)
        
        if web_content is not None:
            web_content_split = web_content.split('\n')
                
            web_content_list = list()
            cur_content = ""
            content_threshold = 4096
            for line in web_content_split:
                # 현재 line이 threshold를 넘는지 확인
                if len(line.strip()) < content_threshold:
                    next_content = cur_content + "\n" + line.strip()
                    if len(next_content) > content_threshold:
                        web_content_list.append(cur_content)
                        cur_content = line.strip()
                    else:
                        cur_content = next_content

            if len(cur_content) > 0:
                web_content_list.append(cur_content)
                
            for content in web_content_list:
                df_dict["word_index"].append(word_index)
                df_dict["word"].append(row["word"])
                df_dict["word_phrase"].append(row["word_phrase"])
                df_dict["senses"].append(row["senses"])
                df_dict["gold_image"].append(row["gold_image"])
                df_dict["gold_pos"].append(row["gold_pos"])
                df_dict["gold_sense"].append(row["gold_sense"])
                df_dict["prompt"].append(prompt_template.format(word=row["word"], entities=valid_entites, context=row["word_phrase"], web_title=cur_title, text_context=content))
            retrieved_urls_num += 1
        else:
            none_page_titles.append(cur_title)
        url_idx += 1
    
    # 마지막으로 3개 추가하는 동안 등장한 None 페이지 제목들을 한꺼번에 요약하도록 프롬프트 생성
    if len(none_page_titles) > 0:
        none_page_titles_str = "\n".join([f"- {title}" for title in none_page_titles])
        df_dict["word_index"].append(word_index)
        df_dict["word"].append(row["word"])
        df_dict["word_phrase"].append(row["word_phrase"])
        df_dict["senses"].append(row["senses"])
        df_dict["gold_image"].append(row["gold_image"])
        df_dict["gold_pos"].append(row["gold_pos"])
        df_dict["gold_sense"].append(row["gold_sense"])
        df_dict["prompt"].append(prompt_template.format(word=row["word"], entities=valid_entites, context=row["word_phrase"], web_title="etc.", text_context=none_page_titles_str))
    
inference_df = pd.DataFrame(df_dict)
inference_df.to_csv("/workspace/data/test_set_process/wsd_100_summarize_prompt3.csv", index=False)

/opt/conda/envs/contrans/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 100/100 [15:24<00:00,  9.24s/it]

#### sub task 2: 요약한 정보로 sense labeling하기

In [4]:
prompt_template="""Text Context: {context}
Ambiguous Word: {word}
---
Sense List:
{sense_list}
---
Image Web Search Results:
{web_search_results}
---
You are an expert linguistic annotator. A specific target word found within the context of a given text, and a list of potential senses for that word are provided. Your task is to determine the correct sense by selecting the one that most directly aligns with the context and its background event.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

First, Use web search results to determine whether there is any background information associated with the given image that cannot be discerned solely from its visual elements. If such information exists, prioritize the sense that best fits this background information, even if it is not the most direct match for the visual content.

Directness of Meaning: If no additional background information can be obtained from the web search results, choose the sense that provides the most direct and specific fit for the visual and linguistic context. Even if a perfect match does not exist, select the sense that is the closest indirect match.
---
After all your reasoning is finished, provide your final decision as the format 'A: [sense number]' and end your generation. In here, [sense number] is the index of your chosen sense from the provided list.
"""

In [5]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")
web_search_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_summarize2_gemma3-27b.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    web_search_results = web_search_df.loc[web_search_df["word"] == row["word"], "generated_text"].tolist()
    
    cropped_web_search_results = ""
    crop_threshold = 3000
    while len(cropped_web_search_results) < crop_threshold and len(web_search_results) > 0:
        next_result = web_search_results.pop(0).strip()
        if next_result != "" and "Not Relevant" not in next_result:
            cropped_web_search_results += (next_result + "\n")
    
    prompt = prompt_template.format(
        word=row["word"],
        context=row["word_phrase"],
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
        web_search_results=cropped_web_search_results
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_100_sense_search2_prompt.csv", index=False)

## 모호한 문장 생성하기

In [12]:
prompt_template="""the {pos} '{word}' that can be interpreted as:
{sense_list}
---
Generate a natural ambiguous sentence using polysemous word '{word}', once so that the sentence can be interpreted in more than one meaning.
In the generated sentence, the {pos} '{word}' should be interpreted as '{gold_sense}'. However, the sentence should not imply any of the given definitions too strongly.
Suggest your final sentence in the format 'Generated Sentence: [your sentence]'. Do not include any explanation, and end your generation after providing the sentence."""

In [13]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")
pos_mapping = {
    "n": "noun",
    "v": "verb",
    "a": "adjective",
    "r": "adverb"
}

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    
    prompt = prompt_template.format(
        word=row["word"],
        pos=pos_mapping.get(row["gold_pos"], row["gold_pos"]),
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
        gold_sense=sense_list[row["gold_sense"] - 1]
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_100_ambiguous_sentence_prompt.csv", index=False)

## 생성된 모호한 문장 평가

### 모호한 문장만을 context로 주고 wsd 수행

In [14]:
prompt_template="""Ambiguous Word: {word}
Text Context: {context}
---
Sense List:
{sense_list}
---
You are an expert linguistic annotator. An ambiguous word found within the context of a given text, and a list of potential senses for that word are provided. Your task is to determine the correct sense by selecting the one that most directly aligns with the context and its background event.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

Prioritize the sense that best fits the given context, even if it is not the most direct match for the visual content.
---
After all your reasoning is finished, provide your final decision as the format 'A: [sense number]' and end your generation. In here, [sense number] is the index of your chosen sense from the provided list.
"""

In [16]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")
ambiguous_sentence_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_ambiguous_sentence_gpt-5.4-nano.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    ambiguous_sentence = ambiguous_sentence_df.loc[ambiguous_sentence_df["word_index"] == row["word_index"], "generated_sentence"].tolist()
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    prompt = prompt_template.format(
        word=row["word"],
        context=ambiguous_sentence[0],
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_100_sense_ambig_sentence_prompt.csv", index=False)

### 생성한 문장과 이미지를 주고 wsd 수행

In [17]:
prompt_template="""Text Context: {context}
Ambiguous Word: {word}
---
Sense List:
{sense_list}
---
You are an expert linguistic annotator. An ambiguous word found within the context of a given text, and a list of potential senses for that word are provided. Your task is to determine the correct sense by selecting the one that most directly aligns with the context and its background event.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

First, take a look at the 'Text Context' and the image. Leverage both context to analyze any significant background context is provided in the image. If such information exists, prioritize the sense that best fits this background information, even if it is not the most direct match for the visual content.

Directness of Meaning: If no additional background information can be obtained from the web search results, choose the sense that provides the most direct and specific fit for the visual and linguistic context. Even if a perfect match does not exist, select the sense that is the closest indirect match.
---
After all your reasoning is finished, provide your final decision as the format 'A: [sense number]' and end your generation. In here, [sense number] is the index of your chosen sense from the provided list.
"""

In [18]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_100_labeled.csv")
ambiguous_sentence_df = pd.read_csv("/workspace/data/test_set_process/inference/wsd_100_ambiguous_sentence_gpt-5.4-nano.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    ambiguous_sentence = ambiguous_sentence_df.loc[ambiguous_sentence_df["word_index"] == row["word_index"], "generated_sentence"].tolist()
    sense_dict = json.loads(row["senses"])
    sense_list = sense_dict.get(row["gold_pos"], [])
    prompt = prompt_template.format(
        word=row["word"],
        context=ambiguous_sentence[0],
        sense_list="\n".join([f" {idx + 1}. {sense}" for idx, sense in enumerate(sense_list)]),
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_100_sense_ambig_sentence_image_prompt.csv", index=False)

# Test set 전체 돌리기

## pos 판별 task

In [ ]:
prompt_template="""
Ambiguous word: {word}
---
{sense_list}

You are an expert linguistic annotator. Image, a specific target word found within the context of that image, and a list of potential senses for that word are given. Each sense is categorized by a Part of Speech (POS): {pos_list}.

Your goal is to determine the correct POS by selecting the sense that most directly aligns with the visual context.
---
Decision Logic & Rules
Follow these rules in order of priority to make your decision:

{rule_list}

Always consider which sense can be most directly and concretely represented in the image. Avoid overcomplicating the reasoning process; focus on the most straightforward interpretation of the visual information in relation to the senses provided.

---
After all your reasoning is finished, provide your final decision as the format 'A: [POS]', where [POS] is your chosen Part of Speech ({pos_list}).
"""

noun_template = """Noun Senses:
{noun_senses}
"""
verb_template = """Verb Senses:
{verb_senses}
"""
adj_template = """Adjective Senses:
{adj_senses}
"""
adv_template = """Adverb Senses:
{adv_senses}
"""

noun_rules = "Every photo features an object. Therefore, consider nouns first."
verb_rules = """Verb is considered when:
* no noun sense is provided.
* the photo depicts an action—either directly or indirectly—rather than the object itself, and if there is a verb sense in the provided list that corresponds to the action shown in the photo."""
adj_rules = """Adjective is considered when:
* the photo can not be considered to depict an object or action of given word.
* the photo depicts a state rather than an action or an object itself, and there is a corresponding sense in the list of adjectives"""
adv_rules = """Adverb is considered when:
* the photo can not be considered to depict an object or action or state of given word."""

In [ ]:
import pandas as pd
import json

wsd_test_df = pd.read_csv("/workspace/data/test_set_process/wsd_set_entire.csv")

prompt_list = list()
for index, row in wsd_test_df.iterrows():
    sense_dict = json.loads(row["senses"])
    noun_senses = sense_dict.get("n", [])
    verb_senses = sense_dict.get("v", [])
    adj_senses = sense_dict.get("a", [])
    adv_senses = sense_dict.get("r", [])
    
    pos_list = list()
    sense_string = ""
    rule_string = ""
    if len(noun_senses) > 0:
        sense_string += (noun_template.format(noun_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(noun_senses)])) + "\n---\n")
        #rule_string += noun_rules + '\n\n'
        pos_list.append("noun")
    if len(verb_senses) > 0:
        sense_string += (verb_template.format(verb_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(verb_senses)])) + "\n---\n")
        rule_string += verb_rules + '\n\n'
        pos_list.append("verb")
    if len(adj_senses) > 0:
        sense_string += (adj_template.format(adj_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(adj_senses)])) + "\n---\n")
        rule_string += adj_rules + '\n\n'
        pos_list.append("adjective")
    if len(adv_senses) > 0:
        sense_string += (adv_template.format(adv_senses="\n".join([f"{i + 1}) {sense}" for i, sense in enumerate(adv_senses)])) + "\n---\n")
        rule_string += adv_rules + '\n\n'
        pos_list.append("adverb")
    
    prompt = prompt_template.format(
        word=row["word"],
        sense_list=sense_string,
        pos_list=", ".join(pos_list),
        rule_list=rule_string,
    )
    prompt_list.append(prompt)

wsd_test_df["prompt"] = prompt_list
wsd_test_df.to_csv("/workspace/data/test_set_process/wsd_set_entire_pos.csv", index=False)